//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHead
    {
        public AccountHead()
        {
            this.AccountHeadOpeningBalances = new HashSet<AccountHeadOpeningBalance>();
            this.CashFlows = new HashSet<CashFlow>();
            this.FutureTransactionOtherAmountTypes = new HashSet<FutureTransactionOtherAmountType>();
            this.FutureTransactions = new HashSet<FutureTransaction>();
            this.JournalDetails = new HashSet<JournalDetail>();
            this.OtherBankTransactions = new HashSet<OtherBankTransaction>();
            this.AccountFlows = new HashSet<AccountFlow>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.Parties = new HashSet<Party>();
            this.AssetTypes = new HashSet<AssetType>();
            this.UniversityMasters = new HashSet<UniversityMaster>();
            this.Employees = new HashSet<Employee>();
            this.UniversityPaymentCancelations = new HashSet<UniversityPaymentCancelation>();
            this.FeeTypes = new HashSet<FeeType>();
        }
    
        public long RowKey { get; set; }
        public string AccountHeadName { get; set; }
        public string AccountHeadCode { get; set; }
        public short AccountHeadTypeKey { get; set; }
        public Nullable<decimal> TotalDebitAmount { get; set; }
        public Nullable<decimal> TotalCreditAmount { get; set; }
        public long DisplayOrder { get; set; }
        public bool IsSystemAccount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> HideDaily { get; set; }
        public Nullable<bool> HideFuture { get; set; }
        public string FutureAccountHeads { get; set; }
        public Nullable<byte> PaymentConfigTypeKey { get; set; }
    
        public virtual AccountHeadType AccountHeadType { get; set; }
        public virtual AccountHeadType AccountHeadType1 { get; set; }
        public virtual ICollection<AccountHeadOpeningBalance> AccountHeadOpeningBalances { get; set; }
        public virtual ICollection<CashFlow> CashFlows { get; set; }
        public virtual ICollection<FutureTransactionOtherAmountType> FutureTransactionOtherAmountTypes { get; set; }
        public virtual ICollection<FutureTransaction> FutureTransactions { get; set; }
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
        public virtual ICollection<OtherBankTransaction> OtherBankTransactions { get; set; }
        public virtual ICollection<AccountFlow> AccountFlows { get; set; }
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<AssetType> AssetTypes { get; set; }
        public virtual ICollection<UniversityMaster> UniversityMasters { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<UniversityPaymentCancelation> UniversityPaymentCancelations { get; set; }
        public virtual ICollection<FeeType> FeeTypes { get; set; }
    }
}
