//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public AccountTransaction()
        {
            this.AccountTransactionPayments = new HashSet<AccountTransactionPayment>();
        }
    
        public long RowKey { get; set; }
        public int AccountLedgerKey { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public long PartyKey { get; set; }
        public byte PartyTypeKey { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> TransactionDueDate { get; set; }
        public Nullable<decimal> DueFineAmount { get; set; }
        public short TransactionStatusKey { get; set; }
        public string Remarks { get; set; }
        public short BranchKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AccountLedger AccountLedger { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual PartyType PartyType { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual ICollection<AccountTransactionPayment> AccountTransactionPayments { get; set; }
    }
}
