//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHeadType
    {
        public AccountHeadType()
        {
            this.AccountHeads = new HashSet<AccountHead>();
            this.AccountHeads1 = new HashSet<AccountHead>();
        }
    
        public short RowKey { get; set; }
        public byte AccountGroupKey { get; set; }
        public string AccountHeadTypeName { get; set; }
        public string AccountHeadTypeCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        public virtual ICollection<AccountHead> AccountHeads { get; set; }
        public virtual ICollection<AccountHead> AccountHeads1 { get; set; }
    }
}
