//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountFlow
    {
        public long RowKey { get; set; }
        public string Purpose { get; set; }
        public decimal Amount { get; set; }
        public byte CashFlowTypeKey { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public byte TransactionTypeKey { get; set; }
        public long TransactionKey { get; set; }
        public short BranchKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public byte VoucherTypeKey { get; set; }
        public long AccountHeadKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CashFlowType CashFlowType { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
