//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalSalaryComponent
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public short AdditionalComponentTypeKey { get; set; }
        public decimal AmountUnit { get; set; }
        public string UnitType { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AdditionalComponentType AdditionalComponentType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
