//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.EmployeeContacts = new HashSet<EmployeeContact>();
        }
    
        public long RowKey { get; set; }
        public short AddressTypeKey { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string CityName { get; set; }
        public int DistrictKey { get; set; }
        public string PostalCode { get; set; }
        public bool NotificationByEmail { get; set; }
        public bool NotificationBySMS { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<EmployeeContact> EmployeeContacts { get; set; }
    }
}
