//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionFee
    {
        public AdmissionFee()
        {
            this.FeeCarryForwordDetails = new HashSet<FeeCarryForwordDetail>();
        }
    
        public long RowKey { get; set; }
        public Nullable<long> ApplicationKey { get; set; }
        public Nullable<int> AdmissionFeeYear { get; set; }
        public Nullable<decimal> AdmissionFeeAmount { get; set; }
        public Nullable<decimal> ConcessionAmount { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<short> FeeTypeKey { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> OldPaid { get; set; }
    
        public virtual AdmissionFee AdmissionFee1 { get; set; }
        public virtual AdmissionFee AdmissionFee2 { get; set; }
        public virtual Application Application { get; set; }
        public virtual FeeType FeeType { get; set; }
        public virtual ICollection<FeeCarryForwordDetail> FeeCarryForwordDetails { get; set; }
    }
}
