//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionNoConfig
    {
        public int RowKey { get; set; }
        public bool IsBranch { get; set; }
        public bool IsBatch { get; set; }
        public bool IsUniversity { get; set; }
        public string LeadingZeros { get; set; }
        public string Combination { get; set; }
    }
}
