//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Applications = new HashSet<Application>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
        }
    
        public int RowKey { get; set; }
        public string AgentName { get; set; }
        public string AgentEmail { get; set; }
        public Nullable<decimal> AgentOpeningBalance { get; set; }
        public string AgentOpeningBalanceType { get; set; }
        public string AgentAddress { get; set; }
        public string AgentPhone { get; set; }
        public string AgentMobile { get; set; }
        public Nullable<bool> AgentActive { get; set; }
        public string AgentCode { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
    }
}
