//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWebForm
    {
        public long RowKey { get; set; }
        public string StudentName { get; set; }
        public string StudentMobile { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPermanentAddress { get; set; }
        public string StudentGuardian { get; set; }
        public Nullable<System.DateTime> StudentDOB { get; set; }
        public Nullable<byte> StudentGender { get; set; }
        public Nullable<short> ReligionKey { get; set; }
        public Nullable<short> CasteKey { get; set; }
        public long CourseKey { get; set; }
        public short UniversityMasterKey { get; set; }
        public short AcademicTermKey { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public Nullable<short> NatureOfEnquiryKey { get; set; }
        public Nullable<int> AgentKey { get; set; }
        public Nullable<byte> CommunityTypeKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool ConvertedToEnquiry { get; set; }
        public Nullable<long> EnquiryKey { get; set; }
        public bool ConvertedToApplication { get; set; }
        public Nullable<long> ApplicationKey { get; set; }
        public bool IsDroped { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> SecondLanguageKey { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
        public string GuardianMobile { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Application Application { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Caste Caste { get; set; }
        public virtual CommunityType CommunityType { get; set; }
        public virtual Course Course { get; set; }
        public virtual NatureOfEnquiry NatureOfEnquiry { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
        public virtual SecondLanguage SecondLanguage { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Enquiry Enquiry { get; set; }
    }
}
