//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.AdmissionFees = new HashSet<AdmissionFee>();
            this.ApplicationFamilyDetails = new HashSet<ApplicationFamilyDetail>();
            this.Attendances = new HashSet<Attendance>();
            this.ExamResults = new HashSet<ExamResult>();
            this.ExamSchedules = new HashSet<ExamSchedule>();
            this.ExamScheduleDetails = new HashSet<ExamScheduleDetail>();
            this.InternalExamResults = new HashSet<InternalExamResult>();
            this.PromotionDetails = new HashSet<PromotionDetail>();
            this.StudentAbsconders = new HashSet<StudentAbsconder>();
            this.StudentDiaries = new HashSet<StudentDiary>();
            this.StudentEarlyDepartures = new HashSet<StudentEarlyDeparture>();
            this.StudentLateDetails = new HashSet<StudentLateDetail>();
            this.StudentLeaveDetails = new HashSet<StudentLeaveDetail>();
            this.StudentsCertificateReturns = new HashSet<StudentsCertificateReturn>();
            this.ElectivePapers = new HashSet<ElectivePaper>();
            this.IssueOfStudyMaterials = new HashSet<IssueOfStudyMaterial>();
            this.StudentDivisionAllocations = new HashSet<StudentDivisionAllocation>();
            this.StudentDocuments = new HashSet<StudentDocument>();
            this.StudentFeeInstallments = new HashSet<StudentFeeInstallment>();
            this.StudentIDCards = new HashSet<StudentIDCard>();
            this.StudentPapers = new HashSet<StudentPaper>();
            this.UnitTestResults = new HashSet<UnitTestResult>();
            this.UniversityCertificates = new HashSet<UniversityCertificate>();
            this.UniversityPaymentMasters = new HashSet<UniversityPaymentMaster>();
            this.EducationQualifications = new HashSet<EducationQualification>();
            this.AppUsers = new HashSet<AppUser>();
            this.ExamTests = new HashSet<ExamTest>();
            this.StudentTCMasters = new HashSet<StudentTCMaster>();
            this.FeeRefundMasters = new HashSet<FeeRefundMaster>();
            this.BonafiedCertificates = new HashSet<BonafiedCertificate>();
            this.CourseCompletionCertificates = new HashSet<CourseCompletionCertificate>();
            this.FeePaymentMasters = new HashSet<FeePaymentMaster>();
            this.StudentCourseTransfers = new HashSet<StudentCourseTransfer>();
            this.TransferAdmissionFees = new HashSet<TransferAdmissionFee>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
            this.ApplicationCertificates = new HashSet<ApplicationCertificate>();
            this.ApplicationFeeFollowups = new HashSet<ApplicationFeeFollowup>();
            this.ApplicationSchedules = new HashSet<ApplicationSchedule>();
        }
    
        public long RowKey { get; set; }
        public string ApplicationNo { get; set; }
        public long CourseKey { get; set; }
        public short UniversityMasterKey { get; set; }
        public string StudentName { get; set; }
        public string StudentGuardian { get; set; }
        public string StudentMotherName { get; set; }
        public string StudentPermanentAddress { get; set; }
        public string StudentPresentAddress { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPhone { get; set; }
        public string StudentMobile { get; set; }
        public System.DateTime StudentDOB { get; set; }
        public short BatchKey { get; set; }
        public byte StudentGender { get; set; }
        public Nullable<short> ReligionKey { get; set; }
        public Nullable<short> IncomeKey { get; set; }
        public Nullable<short> SecondLanguageKey { get; set; }
        public short ModeKey { get; set; }
        public Nullable<short> ClassModeKey { get; set; }
        public Nullable<int> StartYear { get; set; }
        public decimal StudentTotalFee { get; set; }
        public bool StudentClassRequired { get; set; }
        public string StudentClassRequiredDesc { get; set; }
        public Nullable<int> PresentJob_CourseOfStudyId { get; set; }
        public Nullable<short> NatureOfEnquiryKey { get; set; }
        public short BranchKey { get; set; }
        public Nullable<System.DateTime> StudentDateOfAdmission { get; set; }
        public Nullable<int> AgentKey { get; set; }
        public Nullable<short> StudentStatusKey { get; set; }
        public Nullable<int> StudyMaterialIssueStatus { get; set; }
        public string StudentEnrollmentNo { get; set; }
        public string StudentPhotoPath { get; set; }
        public string ExamRegisterNo { get; set; }
        public string Remarks { get; set; }
        public string IsFromEnquiry { get; set; }
        public Nullable<long> EnquiryKey { get; set; }
        public Nullable<short> Mediumkey { get; set; }
        public string AdmissionNo { get; set; }
        public long SerialNumber { get; set; }
        public bool HasInstallment { get; set; }
        public bool HasConcession { get; set; }
        public short CurrentYear { get; set; }
        public Nullable<int> RollNumber { get; set; }
        public short AcademicTermKey { get; set; }
        public bool HasOffer { get; set; }
        public Nullable<int> OfferKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> ClassDetailsKey { get; set; }
        public Nullable<short> CasteKey { get; set; }
        public Nullable<byte> BloodGroupKey { get; set; }
        public Nullable<bool> IsTax { get; set; }
        public bool AllowLogin { get; set; }
        public Nullable<long> AppUserKey { get; set; }
        public string RollNoCode { get; set; }
        public Nullable<byte> CommunityTypeKey { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
        public Nullable<bool> AllowOldPaid { get; set; }
        public short AdmissionCurrentYear { get; set; }
        public Nullable<byte> EducationTypeKey { get; set; }
        public Nullable<short> RegistrationCatagoryKey { get; set; }
        public bool AllowTransportation { get; set; }
        public string TransportLocation { get; set; }
        public string PassPortNumber { get; set; }
        public string EmiratesId { get; set; }
        public string OldStudentPhotoPath { get; set; }
        public string GuardianMobile { get; set; }
        public bool HasBioMetric { get; set; }
        public Nullable<long> BioMetricsId { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual ICollection<AdmissionFee> AdmissionFees { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Caste Caste { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual ICollection<ApplicationFamilyDetail> ApplicationFamilyDetails { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        public virtual ICollection<ExamSchedule> ExamSchedules { get; set; }
        public virtual ICollection<ExamScheduleDetail> ExamScheduleDetails { get; set; }
        public virtual ICollection<InternalExamResult> InternalExamResults { get; set; }
        public virtual ICollection<PromotionDetail> PromotionDetails { get; set; }
        public virtual ICollection<StudentAbsconder> StudentAbsconders { get; set; }
        public virtual ICollection<StudentDiary> StudentDiaries { get; set; }
        public virtual ICollection<StudentEarlyDeparture> StudentEarlyDepartures { get; set; }
        public virtual ICollection<StudentLateDetail> StudentLateDetails { get; set; }
        public virtual ICollection<StudentLeaveDetail> StudentLeaveDetails { get; set; }
        public virtual ICollection<StudentsCertificateReturn> StudentsCertificateReturns { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual ClassMode ClassMode { get; set; }
        public virtual Course Course { get; set; }
        public virtual Income Income { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Mode Mode { get; set; }
        public virtual NatureOfEnquiry NatureOfEnquiry { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual SecondLanguage SecondLanguage { get; set; }
        public virtual StudentStatu StudentStatu { get; set; }
        public virtual ICollection<ElectivePaper> ElectivePapers { get; set; }
        public virtual ICollection<IssueOfStudyMaterial> IssueOfStudyMaterials { get; set; }
        public virtual ICollection<StudentDivisionAllocation> StudentDivisionAllocations { get; set; }
        public virtual ICollection<StudentDocument> StudentDocuments { get; set; }
        public virtual ICollection<StudentFeeInstallment> StudentFeeInstallments { get; set; }
        public virtual ICollection<StudentIDCard> StudentIDCards { get; set; }
        public virtual ICollection<StudentPaper> StudentPapers { get; set; }
        public virtual ICollection<UnitTestResult> UnitTestResults { get; set; }
        public virtual ICollection<UniversityCertificate> UniversityCertificates { get; set; }
        public virtual ICollection<UniversityPaymentMaster> UniversityPaymentMasters { get; set; }
        public virtual CommunityType CommunityType { get; set; }
        public virtual ICollection<EducationQualification> EducationQualifications { get; set; }
        public virtual ICollection<AppUser> AppUsers { get; set; }
        public virtual ICollection<ExamTest> ExamTests { get; set; }
        public virtual ICollection<StudentTCMaster> StudentTCMasters { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<FeeRefundMaster> FeeRefundMasters { get; set; }
        public virtual ICollection<BonafiedCertificate> BonafiedCertificates { get; set; }
        public virtual ICollection<CourseCompletionCertificate> CourseCompletionCertificates { get; set; }
        public virtual ICollection<FeePaymentMaster> FeePaymentMasters { get; set; }
        public virtual RegistratonCatagory RegistratonCatagory { get; set; }
        public virtual ICollection<StudentCourseTransfer> StudentCourseTransfers { get; set; }
        public virtual ICollection<TransferAdmissionFee> TransferAdmissionFees { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
        public virtual Enquiry Enquiry { get; set; }
        public virtual ICollection<ApplicationCertificate> ApplicationCertificates { get; set; }
        public virtual ICollection<ApplicationFeeFollowup> ApplicationFeeFollowups { get; set; }
        public virtual ICollection<ApplicationSchedule> ApplicationSchedules { get; set; }
        public virtual EsslStudent EsslStudent { get; set; }
    }
}
