//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationType
    {
        public ApplicationType()
        {
            this.MemberPlanDetails = new HashSet<MemberPlanDetail>();
        }
    
        public byte RowKey { get; set; }
        public string ApplicationTypeName { get; set; }
    
        public virtual ICollection<MemberPlanDetail> MemberPlanDetails { get; set; }
    }
}
