//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFamilyDetail
    {
        public long RowKey { get; set; }
        public Nullable<short> FamilyMemberTypeKey { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public bool SendMail { get; set; }
        public bool sendSMS { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<long> AppuserKey { get; set; }
        public bool IfLogin { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Address { get; set; }
    
        public virtual FamilyMemberType FamilyMemberType { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual Application Application { get; set; }
    }
}
