//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFeeFollowup
    {
        public ApplicationFeeFollowup()
        {
            this.ExtendFeeFollowUpDates = new HashSet<ExtendFeeFollowUpDate>();
            this.FeeFollowUpFeeTypes = new HashSet<FeeFollowUpFeeType>();
        }
    
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> ProcessStatusKey { get; set; }
        public bool IfExtendDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual ICollection<ExtendFeeFollowUpDate> ExtendFeeFollowUpDates { get; set; }
        public virtual ICollection<FeeFollowUpFeeType> FeeFollowUpFeeTypes { get; set; }
    }
}
