//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDetail
    {
        public long RowKey { get; set; }
        public string AssetDetailName { get; set; }
        public int AssetTypeKey { get; set; }
        public string AssetDetailCode { get; set; }
        public byte PeriodTypeKey { get; set; }
        public short LifePeriod { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public bool IsActive { get; set; }
        public decimal Amount { get; set; }
        public decimal Depreciation { get; set; }
        public short BranchKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual AssetType AssetType { get; set; }
    }
}
