//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetType
    {
        public AssetType()
        {
            this.AssetDetails = new HashSet<AssetDetail>();
            this.AssetPurchaseDetails = new HashSet<AssetPurchaseDetail>();
        }
    
        public int RowKey { get; set; }
        public string AssetTypeName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public bool IsTax { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<long> HSNCodeKey { get; set; }
        public Nullable<int> RefKey { get; set; }
        public bool HaveDepreciation { get; set; }
        public byte DepreciationMethodKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public long AccountHeadKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual ICollection<AssetDetail> AssetDetails { get; set; }
        public virtual ICollection<AssetPurchaseDetail> AssetPurchaseDetails { get; set; }
        public virtual DepreciationMethod DepreciationMethod { get; set; }
        public virtual HSNCodeMaster HSNCodeMaster { get; set; }
    }
}
