//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPurchaseDetail
    {
        public AssetPurchaseDetail()
        {
            this.DepreciationDetails = new HashSet<DepreciationDetail>();
        }
    
        public long RowKey { get; set; }
        public int AssetTypeKey { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public byte RateTypeKey { get; set; }
        public long OrderMasterKey { get; set; }
        public Nullable<decimal> RowTotal { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> RateTypeUnitLength { get; set; }
        public Nullable<decimal> RowTotalGST { get; set; }
        public Nullable<long> RefKey { get; set; }
        public byte PeriodTypeKey { get; set; }
        public short LifePeriod { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<decimal> Depreciation { get; set; }
        public byte DepreciationMethodKey { get; set; }
        public Nullable<decimal> ProductionLimit { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AssetPurchaseMaster AssetPurchaseMaster { get; set; }
        public virtual DepreciationMethod DepreciationMethod { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual ICollection<DepreciationDetail> DepreciationDetails { get; set; }
        public virtual AssetType AssetType { get; set; }
    }
}
