//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public long RowKey { get; set; }
        public long AttendanceMasterKey { get; set; }
        public short AttendanceTypeKey { get; set; }
        public bool AttendanceStatus { get; set; }
        public string Remarks { get; set; }
        public byte AttendanceStatusKey { get; set; }
        public Nullable<long> StudentLateKey { get; set; }
        public Nullable<long> StudentLeaveKey { get; set; }
        public Nullable<long> StudentEarlyDepartureKey { get; set; }
        public Nullable<long> StudentAbscondersKey { get; set; }
        public Nullable<System.TimeSpan> ClassInTime { get; set; }
        public Nullable<System.DateTime> PunchInTime { get; set; }
        public Nullable<int> LateMinutes { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual AttendanceStatu AttendanceStatu { get; set; }
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual StudentAbsconder StudentAbsconder { get; set; }
        public virtual StudentEarlyDeparture StudentEarlyDeparture { get; set; }
        public virtual StudentLateDetail StudentLateDetail { get; set; }
        public virtual StudentLeaveDetail StudentLeaveDetail { get; set; }
    }
}
