//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceConfigType
    {
        public AttendanceConfigType()
        {
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.AttendanceConfigurations = new HashSet<AttendanceConfiguration>();
            this.Employees = new HashSet<Employee>();
        }
    
        public byte RowKey { get; set; }
        public string AttendanceConfigTypeName { get; set; }
    
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<AttendanceConfiguration> AttendanceConfigurations { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
