//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTypeMaster
    {
        public AttendanceTypeMaster()
        {
            this.AttendanceTypeDetails = new HashSet<AttendanceTypeDetail>();
            this.AttendanceTypeMasterClasses = new HashSet<AttendanceTypeMasterClass>();
        }
    
        public short RowKey { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<AttendanceTypeDetail> AttendanceTypeDetails { get; set; }
        public virtual ICollection<AttendanceTypeMasterClass> AttendanceTypeMasterClasses { get; set; }
    }
}
