//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public Attendance()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
        }
    
        public long RowKey { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public short BranchKey { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
        public long ClassDetailsKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<int> RollNumber { get; set; }
        public Nullable<short> BatchKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> AttendanceLogId { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
