//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceStatu
    {
        public AttendanceStatu()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
        }
    
        public byte RowKey { get; set; }
        public string AttendanceStatusCode { get; set; }
        public string AttendanceStatusName { get; set; }
        public string AttendanceStatusColor { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
    }
}
