//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceConfiguration
    {
        public int RowKey { get; set; }
        public Nullable<short> CompanyKey { get; set; }
        public byte AttendanceConfigTypeKey { get; set; }
        public Nullable<int> ShiftKey { get; set; }
        public decimal TotalWorkingHours { get; set; }
        public Nullable<decimal> OvertimeAdditionAmount { get; set; }
        public Nullable<byte> UnitTypeKey { get; set; }
        public Nullable<decimal> BaseDaysPerMonth { get; set; }
        public bool AutoApproval { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> MinimmDifferencePunch { get; set; }
        public Nullable<short> BranchKey { get; set; }
    
        public virtual AttendanceConfigType AttendanceConfigType { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
