//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCategory
    {
        public AttendanceCategory()
        {
            this.AttendanceCategoryWeekOffs = new HashSet<AttendanceCategoryWeekOff>();
            this.Employees = new HashSet<Employee>();
        }
    
        public short RowKey { get; set; }
        public string AttendanceCategoryCode { get; set; }
        public string AttendanceCategoryName { get; set; }
        public byte OverTimeFormulaKey { get; set; }
        public Nullable<int> MinOvertime { get; set; }
        public Nullable<int> MaxOvertime { get; set; }
        public Nullable<bool> ConsiderFirstLastPunch { get; set; }
        public Nullable<int> LateComingGraceTime { get; set; }
        public Nullable<int> EarlyGoingGraceTime { get; set; }
        public Nullable<bool> ConsiderEarlyPunch { get; set; }
        public Nullable<bool> ConsiderLatePunch { get; set; }
        public Nullable<bool> DeductBrakeHours { get; set; }
        public Nullable<bool> CalcuteHalfDay { get; set; }
        public Nullable<int> HalfDayMins { get; set; }
        public Nullable<bool> CalculateAbsent { get; set; }
        public Nullable<int> AbsentMins { get; set; }
        public Nullable<bool> PartCalculateHalfDay { get; set; }
        public Nullable<int> PartHalfDayMins { get; set; }
        public Nullable<bool> PartCalculateAbsent { get; set; }
        public Nullable<int> PartAbsentMins { get; set; }
        public Nullable<bool> WOandHAsPreDayAbsent { get; set; }
        public Nullable<bool> WOandHAsSufDayAbsent { get; set; }
        public Nullable<bool> WOandHAsBothDayAbsent { get; set; }
        public Nullable<bool> MarkAsAbsentForLate { get; set; }
        public Nullable<int> ContiousLateDay { get; set; }
        public Nullable<byte> AbsentDayType { get; set; }
        public Nullable<bool> MarkHalfdayForLaterGoing { get; set; }
        public Nullable<int> HalfDayLateByMins { get; set; }
        public Nullable<bool> MarkHalfdayForEarlyGoing { get; set; }
        public Nullable<int> HalfDayEarlyByMins { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> RefKey { get; set; }
    
        public virtual OverTimeFormulaType OverTimeFormulaType { get; set; }
        public virtual ICollection<AttendanceCategoryWeekOff> AttendanceCategoryWeekOffs { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
