//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceType
    {
        public AttendanceType()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
            this.AttendanceTypeDetails = new HashSet<AttendanceTypeDetail>();
        }
    
        public short RowKey { get; set; }
        public string AttendanceTypeName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> GraceTime { get; set; }
    
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual ICollection<AttendanceTypeDetail> AttendanceTypeDetails { get; set; }
    }
}
