//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public long RowKey { get; set; }
        public string TableName { get; set; }
        public string ActionName { get; set; }
        public string PrimaryKey { get; set; }
        public string ChangedValues { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
    }
}
