//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandStatu
    {
        public byte RowKey { get; set; }
        public string BandStatusName { get; set; }
        public decimal BandScore { get; set; }
        public string BandColor { get; set; }
    }
}
