//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public BankAccount()
        {
            this.AccountTransactionPayments = new HashSet<AccountTransactionPayment>();
            this.AssetPurchasePayments = new HashSet<AssetPurchasePayment>();
            this.BankReconciliations = new HashSet<BankReconciliation>();
            this.BankStatementMasters = new HashSet<BankStatementMaster>();
            this.BankTransactions = new HashSet<BankTransaction>();
            this.BankTransactions1 = new HashSet<BankTransaction>();
            this.BranchAccounts = new HashSet<BranchAccount>();
            this.CashFlows = new HashSet<CashFlow>();
            this.ChequeClearances = new HashSet<ChequeClearance>();
            this.EmployeeLoanPayments = new HashSet<EmployeeLoanPayment>();
            this.EmployeeSalaryAdvancePayments = new HashSet<EmployeeSalaryAdvancePayment>();
            this.EmployeeSalaryAdvanceReturnMasters = new HashSet<EmployeeSalaryAdvanceReturnMaster>();
            this.EmployeeSalaryPayments = new HashSet<EmployeeSalaryPayment>();
            this.FutureTransactionPayments = new HashSet<FutureTransactionPayment>();
            this.OtherBankTransactions = new HashSet<OtherBankTransaction>();
            this.UniversityPaymentMasters = new HashSet<UniversityPaymentMaster>();
            this.FeeRefundMasters = new HashSet<FeeRefundMaster>();
            this.FeePaymentMasters = new HashSet<FeePaymentMaster>();
        }
    
        public long RowKey { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public short BankKey { get; set; }
        public string BranchLocation { get; set; }
        public string IFSCCode { get; set; }
        public string AccountNumber { get; set; }
        public string NameInAccount { get; set; }
        public short AccountTypeKey { get; set; }
        public string MICRCode { get; set; }
        public Nullable<decimal> OpeningAccountBalance { get; set; }
        public Nullable<decimal> CurrentAccountBalance { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public long AccountHeadKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual ICollection<AccountTransactionPayment> AccountTransactionPayments { get; set; }
        public virtual ICollection<AssetPurchasePayment> AssetPurchasePayments { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual BankAccountType BankAccountType { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<BankReconciliation> BankReconciliations { get; set; }
        public virtual ICollection<BankStatementMaster> BankStatementMasters { get; set; }
        public virtual ICollection<BankTransaction> BankTransactions { get; set; }
        public virtual ICollection<BankTransaction> BankTransactions1 { get; set; }
        public virtual ICollection<BranchAccount> BranchAccounts { get; set; }
        public virtual ICollection<CashFlow> CashFlows { get; set; }
        public virtual ICollection<ChequeClearance> ChequeClearances { get; set; }
        public virtual ICollection<EmployeeLoanPayment> EmployeeLoanPayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvancePayment> EmployeeSalaryAdvancePayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvanceReturnMaster> EmployeeSalaryAdvanceReturnMasters { get; set; }
        public virtual ICollection<EmployeeSalaryPayment> EmployeeSalaryPayments { get; set; }
        public virtual ICollection<FutureTransactionPayment> FutureTransactionPayments { get; set; }
        public virtual ICollection<OtherBankTransaction> OtherBankTransactions { get; set; }
        public virtual ICollection<UniversityPaymentMaster> UniversityPaymentMasters { get; set; }
        public virtual ICollection<FeeRefundMaster> FeeRefundMasters { get; set; }
        public virtual ICollection<FeePaymentMaster> FeePaymentMasters { get; set; }
    }
}
