//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatementMaster
    {
        public BankStatementMaster()
        {
            this.BankStatementDetails = new HashSet<BankStatementDetail>();
        }
    
        public long RowKey { get; set; }
        public long BankAccountKey { get; set; }
        public short BranchKey { get; set; }
        public byte MonthKey { get; set; }
        public int YearKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<BankStatementDetail> BankStatementDetails { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
