//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankReconciliation
    {
        public long RowKey { get; set; }
        public byte TransactionTypeKey { get; set; }
        public long TransactionKey { get; set; }
        public short ProcessStatusKey { get; set; }
        public Nullable<long> BankStatementKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Purpose { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<byte> CashFlowTypeKey { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public string Remark { get; set; }
    
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual CashFlowType CashFlowType { get; set; }
        public virtual BankStatementDetail BankStatementDetail { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
