//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransactionType
    {
        public BankTransactionType()
        {
            this.BankTransactions = new HashSet<BankTransaction>();
            this.BankStatementDetails = new HashSet<BankStatementDetail>();
        }
    
        public byte RowKey { get; set; }
        public string BankTransactionTypeName { get; set; }
        public string BankTransactionTypeCode { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<BankTransaction> BankTransactions { get; set; }
        public virtual ICollection<BankStatementDetail> BankStatementDetails { get; set; }
    }
}
