//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatementDetail
    {
        public BankStatementDetail()
        {
            this.BankReconciliations = new HashSet<BankReconciliation>();
            this.OtherBankTransactions = new HashSet<OtherBankTransaction>();
        }
    
        public long RowKey { get; set; }
        public string ReferenceKey { get; set; }
        public string Particulars { get; set; }
        public Nullable<byte> BankTransactionTypeKey { get; set; }
        public byte CashFlowTypeKey { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public long MasterKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> RefKey { get; set; }
    
        public virtual ICollection<BankReconciliation> BankReconciliations { get; set; }
        public virtual BankStatementMaster BankStatementMaster { get; set; }
        public virtual BankTransactionType BankTransactionType { get; set; }
        public virtual CashFlowType CashFlowType { get; set; }
        public virtual ICollection<OtherBankTransaction> OtherBankTransactions { get; set; }
    }
}
