//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.ExamScheduleMasters = new HashSet<ExamScheduleMaster>();
            this.InternalExams = new HashSet<InternalExam>();
            this.Promotions = new HashSet<Promotion>();
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.UnitTestSchedules = new HashSet<UnitTestSchedule>();
            this.Attendances = new HashSet<Attendance>();
            this.StudentDivisionAllocations = new HashSet<StudentDivisionAllocation>();
            this.Applications = new HashSet<Application>();
            this.TeacherClassAllocations = new HashSet<TeacherClassAllocation>();
            this.StudentAbsconders = new HashSet<StudentAbsconder>();
            this.StudentEarlyDepartures = new HashSet<StudentEarlyDeparture>();
            this.StudentLateDetails = new HashSet<StudentLateDetail>();
            this.StudentLeaveDetails = new HashSet<StudentLeaveDetail>();
        }
    
        public short RowKey { get; set; }
        public string BatchName { get; set; }
        public string BatchCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> DurationFromYear { get; set; }
        public Nullable<short> DurationToYear { get; set; }
        public Nullable<System.DateTime> DurationFromDate { get; set; }
        public Nullable<System.DateTime> DurationToDate { get; set; }
    
        public virtual ICollection<ExamScheduleMaster> ExamScheduleMasters { get; set; }
        public virtual ICollection<InternalExam> InternalExams { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<UnitTestSchedule> UnitTestSchedules { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<StudentDivisionAllocation> StudentDivisionAllocations { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<TeacherClassAllocation> TeacherClassAllocations { get; set; }
        public virtual ICollection<StudentAbsconder> StudentAbsconders { get; set; }
        public virtual ICollection<StudentEarlyDeparture> StudentEarlyDepartures { get; set; }
        public virtual ICollection<StudentLateDetail> StudentLateDetails { get; set; }
        public virtual ICollection<StudentLeaveDetail> StudentLeaveDetails { get; set; }
    }
}
