//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public BloodGroup()
        {
            this.Applications = new HashSet<Application>();
            this.Employees = new HashSet<Employee>();
        }
    
        public byte RowKey { get; set; }
        public string BloodGroupName { get; set; }
        public string BloodGroupNameLocal { get; set; }
        public byte DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
