//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStatu
    {
        public BookStatu()
        {
            this.BookCopies = new HashSet<BookCopy>();
            this.BookIssueReturnDetails = new HashSet<BookIssueReturnDetail>();
        }
    
        public byte RowKey { get; set; }
        public string BookStatusName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool CanIssue { get; set; }
    
        public virtual ICollection<BookCopy> BookCopies { get; set; }
        public virtual ICollection<BookIssueReturnDetail> BookIssueReturnDetails { get; set; }
    }
}
