//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssueReturnMaster
    {
        public BookIssueReturnMaster()
        {
            this.BookIssueReturnDetails = new HashSet<BookIssueReturnDetail>();
        }
    
        public int RowKey { get; set; }
        public Nullable<long> MemberRegistrationKey { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<BookIssueReturnDetail> BookIssueReturnDetails { get; set; }
        public virtual MemberPlanDetail MemberPlanDetail { get; set; }
    }
}
