//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopy
    {
        public BookCopy()
        {
            this.BookIssueReturnDetails = new HashSet<BookIssueReturnDetail>();
        }
    
        public long RowKey { get; set; }
        public long BookKey { get; set; }
        public string BookCopySlNo { get; set; }
        public long SerialNo { get; set; }
        public string ISBN { get; set; }
        public string BookBarCode { get; set; }
        public string BookEdition { get; set; }
        public Nullable<short> BookPrintYear { get; set; }
        public Nullable<short> NoOfPages { get; set; }
        public decimal BookPrice { get; set; }
        public decimal FineAmount { get; set; }
        public bool IsIssued { get; set; }
        public Nullable<byte> BookStatusKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LibraryBook LibraryBook { get; set; }
        public virtual BookStatu BookStatu { get; set; }
        public virtual ICollection<BookIssueReturnDetail> BookIssueReturnDetails { get; set; }
    }
}
