//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssueType
    {
        public BookIssueType()
        {
            this.LibraryBooks = new HashSet<LibraryBook>();
        }
    
        public byte RowKey { get; set; }
        public string BookIssueTypeName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<LibraryBook> LibraryBooks { get; set; }
    }
}
