//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.StudentPapers = new HashSet<StudentPaper>();
        }
    
        public long RowKey { get; set; }
        public string BookCode { get; set; }
        public string BookName { get; set; }
        public long CourseKey { get; set; }
        public short UniversityKey { get; set; }
        public Nullable<int> BatchKey { get; set; }
        public short BookYear { get; set; }
        public string BookType { get; set; }
        public bool HasBook { get; set; }
        public bool IsActive { get; set; }
        public short AcademicTermKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual Course Course { get; set; }
        public virtual Book Books1 { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual ICollection<StudentPaper> StudentPapers { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
    }
}
