//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowerType
    {
        public BorrowerType()
        {
            this.MemberPlanDetails = new HashSet<MemberPlanDetail>();
        }
    
        public byte RowKey { get; set; }
        public string BorrowerTypeName { get; set; }
        public byte NoOfBookIssueAtATime { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BorrowerTypeCode { get; set; }
    
        public virtual ICollection<MemberPlanDetail> MemberPlanDetails { get; set; }
    }
}
