//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchAccount
    {
        public int RowKey { get; set; }
        public short BranchKey { get; set; }
        public long BankAccountKey { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
