//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.AccountHeadOpeningBalances = new HashSet<AccountHeadOpeningBalance>();
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.BankStatementMasters = new HashSet<BankStatementMaster>();
            this.BankTransactions = new HashSet<BankTransaction>();
            this.BranchDepartments = new HashSet<BranchDepartment>();
            this.CashFlows = new HashSet<CashFlow>();
            this.ExamScheduleMasters = new HashSet<ExamScheduleMaster>();
            this.FutureTransactionPayments = new HashSet<FutureTransactionPayment>();
            this.FutureTransactions = new HashSet<FutureTransaction>();
            this.InternalExams = new HashSet<InternalExam>();
            this.JournalMasters = new HashSet<JournalMaster>();
            this.LibraryBooks = new HashSet<LibraryBook>();
            this.MemberPlanDetails = new HashSet<MemberPlanDetail>();
            this.MemberRegistrations = new HashSet<MemberRegistration>();
            this.PaymentReceiptNumberConfigurations = new HashSet<PaymentReceiptNumberConfiguration>();
            this.Promotions = new HashSet<Promotion>();
            this.Racks = new HashSet<Rack>();
            this.Scholarships = new HashSet<Scholarship>();
            this.ScholarshipExamSchedules = new HashSet<ScholarshipExamSchedule>();
            this.SubBranches = new HashSet<SubBranch>();
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.UnitTestSchedules = new HashSet<UnitTestSchedule>();
            this.Attendances = new HashSet<Attendance>();
            this.Applications = new HashSet<Application>();
            this.Holidays = new HashSet<Holiday>();
            this.AssetDetails = new HashSet<AssetDetail>();
            this.AssetPurchasePayments = new HashSet<AssetPurchasePayment>();
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.AttendanceConfigurations = new HashSet<AttendanceConfiguration>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.BranchAccounts = new HashSet<BranchAccount>();
            this.AccountFlows = new HashSet<AccountFlow>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.Parties = new HashSet<Party>();
            this.Employees = new HashSet<Employee>();
            this.CashTransactions = new HashSet<CashTransaction>();
            this.CashTransactions1 = new HashSet<CashTransaction>();
            this.UniversityPaymentMasters = new HashSet<UniversityPaymentMaster>();
            this.FeeRefundMasters = new HashSet<FeeRefundMaster>();
            this.FeePaymentMasters = new HashSet<FeePaymentMaster>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
            this.Enquiries = new HashSet<Enquiry>();
            this.Enquiries1 = new HashSet<Enquiry>();
            this.EmployeeSalaryPayments = new HashSet<EmployeeSalaryPayment>();
            this.EmployeeSalaryAdvancePayments = new HashSet<EmployeeSalaryAdvancePayment>();
            this.EmployeeSalaryAdvanceReturnMasters = new HashSet<EmployeeSalaryAdvanceReturnMaster>();
            this.StudentTimeTables = new HashSet<StudentTimeTable>();
        }
    
        public short RowKey { get; set; }
        public short CompanyKey { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchNameLocal { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string CityName { get; set; }
        public int DistrictKey { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> OpeningCashBalance { get; set; }
        public Nullable<decimal> CurrentCashBalance { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonPhone { get; set; }
        public Nullable<short> DesignationKey { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<byte> TotalWorkingDays { get; set; }
        public Nullable<byte> TotalWorkingHours { get; set; }
        public bool IsFranchise { get; set; }
        public string BranchLogo { get; set; }
    
        public virtual ICollection<AccountHeadOpeningBalance> AccountHeadOpeningBalances { get; set; }
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        public virtual ICollection<BankStatementMaster> BankStatementMasters { get; set; }
        public virtual ICollection<BankTransaction> BankTransactions { get; set; }
        public virtual Company Company { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<BranchDepartment> BranchDepartments { get; set; }
        public virtual ICollection<CashFlow> CashFlows { get; set; }
        public virtual ICollection<ExamScheduleMaster> ExamScheduleMasters { get; set; }
        public virtual ICollection<FutureTransactionPayment> FutureTransactionPayments { get; set; }
        public virtual ICollection<FutureTransaction> FutureTransactions { get; set; }
        public virtual ICollection<InternalExam> InternalExams { get; set; }
        public virtual ICollection<JournalMaster> JournalMasters { get; set; }
        public virtual ICollection<LibraryBook> LibraryBooks { get; set; }
        public virtual ICollection<MemberPlanDetail> MemberPlanDetails { get; set; }
        public virtual ICollection<MemberRegistration> MemberRegistrations { get; set; }
        public virtual ICollection<PaymentReceiptNumberConfiguration> PaymentReceiptNumberConfigurations { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<Rack> Racks { get; set; }
        public virtual ICollection<Scholarship> Scholarships { get; set; }
        public virtual ICollection<ScholarshipExamSchedule> ScholarshipExamSchedules { get; set; }
        public virtual ICollection<SubBranch> SubBranches { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<UnitTestSchedule> UnitTestSchedules { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<AssetDetail> AssetDetails { get; set; }
        public virtual ICollection<AssetPurchasePayment> AssetPurchasePayments { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<AttendanceConfiguration> AttendanceConfigurations { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<BranchAccount> BranchAccounts { get; set; }
        public virtual ICollection<AccountFlow> AccountFlows { get; set; }
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<CashTransaction> CashTransactions { get; set; }
        public virtual ICollection<CashTransaction> CashTransactions1 { get; set; }
        public virtual ICollection<UniversityPaymentMaster> UniversityPaymentMasters { get; set; }
        public virtual ICollection<FeeRefundMaster> FeeRefundMasters { get; set; }
        public virtual ICollection<FeePaymentMaster> FeePaymentMasters { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        public virtual ICollection<Enquiry> Enquiries1 { get; set; }
        public virtual ICollection<EmployeeSalaryPayment> EmployeeSalaryPayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvancePayment> EmployeeSalaryAdvancePayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvanceReturnMaster> EmployeeSalaryAdvanceReturnMasters { get; set; }
        public virtual ICollection<StudentTimeTable> StudentTimeTables { get; set; }
    }
}
