//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingDetail
    {
        public BuildingDetail()
        {
            this.ClassDetails = new HashSet<ClassDetail>();
        }
    
        public long RowKey { get; set; }
        public int BuildingMasterKey { get; set; }
        public string BuildingDetailsName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual BuildingMaster BuildingMaster { get; set; }
        public virtual ICollection<ClassDetail> ClassDetails { get; set; }
    }
}
