//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkSMSTrack
    {
        public BulkSMSTrack()
        {
            this.BulkSMSTrackDetails = new HashSet<BulkSMSTrackDetail>();
            this.BulkSMSTrackDetails1 = new HashSet<BulkSMSTrackDetail>();
            this.BulkSMSTrackDetails2 = new HashSet<BulkSMSTrackDetail>();
            this.BulkSMSTrackDetails3 = new HashSet<BulkSMSTrackDetail>();
        }
    
        public long RowKey { get; set; }
        public string SMSContent { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long AddedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<BulkSMSTrackDetail> BulkSMSTrackDetails { get; set; }
        public virtual ICollection<BulkSMSTrackDetail> BulkSMSTrackDetails1 { get; set; }
        public virtual ICollection<BulkSMSTrackDetail> BulkSMSTrackDetails2 { get; set; }
        public virtual ICollection<BulkSMSTrackDetail> BulkSMSTrackDetails3 { get; set; }
    }
}
