//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkEmailTrackDetail
    {
        public long RowKey { get; set; }
        public string ToEmail { get; set; }
        public Nullable<long> BulkEmailTrackKey { get; set; }
        public Nullable<long> UserRowKey { get; set; }
        public Nullable<short> RoleKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long AddedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual BulkEmailTrack BulkEmailTrack { get; set; }
        public virtual BulkEmailTrack BulkEmailTrack1 { get; set; }
        public virtual BulkEmailTrack BulkEmailTrack2 { get; set; }
        public virtual BulkEmailTrack BulkEmailTrack3 { get; set; }
    }
}
