//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkEmailTrack
    {
        public BulkEmailTrack()
        {
            this.BulkEmailTrackDetails = new HashSet<BulkEmailTrackDetail>();
            this.BulkEmailTrackDetails1 = new HashSet<BulkEmailTrackDetail>();
            this.BulkEmailTrackDetails2 = new HashSet<BulkEmailTrackDetail>();
            this.BulkEmailTrackDetails3 = new HashSet<BulkEmailTrackDetail>();
        }
    
        public long RowKey { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContentFileName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long AddedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<BulkEmailTrackDetail> BulkEmailTrackDetails { get; set; }
        public virtual ICollection<BulkEmailTrackDetail> BulkEmailTrackDetails1 { get; set; }
        public virtual ICollection<BulkEmailTrackDetail> BulkEmailTrackDetails2 { get; set; }
        public virtual ICollection<BulkEmailTrackDetail> BulkEmailTrackDetails3 { get; set; }
    }
}
