//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallType
    {
        public CallType()
        {
            this.EnquiryFeedbacks = new HashSet<EnquiryFeedback>();
            this.EnquiryLeadFeedbacks = new HashSet<EnquiryLeadFeedback>();
            this.ApplicationSchedules = new HashSet<ApplicationSchedule>();
        }
    
        public byte RowKey { get; set; }
        public string CallTypeName { get; set; }
    
        public virtual ICollection<EnquiryFeedback> EnquiryFeedbacks { get; set; }
        public virtual ICollection<EnquiryLeadFeedback> EnquiryLeadFeedbacks { get; set; }
        public virtual ICollection<ApplicationSchedule> ApplicationSchedules { get; set; }
    }
}
