//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlow
    {
        public long RowKey { get; set; }
        public long AccountHeadKey { get; set; }
        public Nullable<short> ChequeStatusKey { get; set; }
        public System.DateTime CashFlowDate { get; set; }
        public byte CashFlowTypeKey { get; set; }
        public string VoucherNumber { get; set; }
        public decimal Amount { get; set; }
        public short PaymentModeKey { get; set; }
        public string CardNumber { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public string ChequeOrDDNumber { get; set; }
        public Nullable<System.DateTime> ChequeOrDDDate { get; set; }
        public Nullable<decimal> AccountBalanceAmount { get; set; }
        public Nullable<byte> TransactionTypeKey { get; set; }
        public Nullable<long> TransactionKey { get; set; }
        public string Purpose { get; set; }
        public string PaidBy { get; set; }
        public string AuthorizedBy { get; set; }
        public string ReceivedBy { get; set; }
        public string OnBehalfOf { get; set; }
        public string Remarks { get; set; }
        public short BranchKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<bool> IsContra { get; set; }
        public Nullable<long> SerialNumber { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<short> PaymentModeSubKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CashFlowType CashFlowType { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentModeSub PaymentModeSub { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
