//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlowType
    {
        public CashFlowType()
        {
            this.AccountLedgerTypes = new HashSet<AccountLedgerType>();
            this.BankReconciliations = new HashSet<BankReconciliation>();
            this.CashFlows = new HashSet<CashFlow>();
            this.FutureTransactionPayments = new HashSet<FutureTransactionPayment>();
            this.FutureTransactions = new HashSet<FutureTransaction>();
            this.FutureTransactions1 = new HashSet<FutureTransaction>();
            this.BankStatementDetails = new HashSet<BankStatementDetail>();
            this.AccountFlows = new HashSet<AccountFlow>();
            this.FeeTypes = new HashSet<FeeType>();
        }
    
        public byte RowKey { get; set; }
        public string CashFlowTypeName { get; set; }
    
        public virtual ICollection<AccountLedgerType> AccountLedgerTypes { get; set; }
        public virtual ICollection<BankReconciliation> BankReconciliations { get; set; }
        public virtual ICollection<CashFlow> CashFlows { get; set; }
        public virtual ICollection<FutureTransactionPayment> FutureTransactionPayments { get; set; }
        public virtual ICollection<FutureTransaction> FutureTransactions { get; set; }
        public virtual ICollection<FutureTransaction> FutureTransactions1 { get; set; }
        public virtual ICollection<BankStatementDetail> BankStatementDetails { get; set; }
        public virtual ICollection<AccountFlow> AccountFlows { get; set; }
        public virtual ICollection<FeeType> FeeTypes { get; set; }
    }
}
