//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransaction
    {
        public long RowKey { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<short> FromBranchKey { get; set; }
        public Nullable<short> ToBranchKey { get; set; }
        public decimal Amount { get; set; }
        public string Purpose { get; set; }
        public string PaidBy { get; set; }
        public string AuthorizedBy { get; set; }
        public string ReceivedBy { get; set; }
        public string OnBehalfOf { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> SerialNumber { get; set; }
        public string ReceiptNumber { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
    }
}
