//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateType
    {
        public CertificateType()
        {
            this.UniversityCertificates = new HashSet<UniversityCertificate>();
            this.ApplicationCertificates = new HashSet<ApplicationCertificate>();
        }
    
        public short RowKey { get; set; }
        public string CertificateTypeName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<UniversityCertificate> UniversityCertificates { get; set; }
        public virtual ICollection<ApplicationCertificate> ApplicationCertificates { get; set; }
    }
}
