//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeClearance
    {
        public long RowKey { get; set; }
        public System.DateTime ClearanceDate { get; set; }
        public short PaymentModeKey { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public byte TransactionTypeKey { get; set; }
        public long TransactionKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Purpose { get; set; }
        public bool IsApproved { get; set; }
        public string Remark { get; set; }
        public Nullable<long> RefKey { get; set; }
        public Nullable<short> PaymentModeSubKey { get; set; }
    
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentModeSub PaymentModeSub { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
