//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDetail
    {
        public ClassDetail()
        {
            this.PromotionDetails = new HashSet<PromotionDetail>();
            this.InternalExamDivisions = new HashSet<InternalExamDivision>();
            this.InternalExamResults = new HashSet<InternalExamResult>();
            this.Promotions = new HashSet<Promotion>();
            this.TeacherSubjectAllocations = new HashSet<TeacherSubjectAllocation>();
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.UnitTestSchedules = new HashSet<UnitTestSchedule>();
            this.Attendances = new HashSet<Attendance>();
            this.StudentAbsconders = new HashSet<StudentAbsconder>();
            this.StudentDiaries = new HashSet<StudentDiary>();
            this.StudentDivisionAllocations = new HashSet<StudentDivisionAllocation>();
            this.StudentEarlyDepartures = new HashSet<StudentEarlyDeparture>();
            this.StudentLateDetails = new HashSet<StudentLateDetail>();
            this.StudentLeaveDetails = new HashSet<StudentLeaveDetail>();
            this.Applications = new HashSet<Application>();
            this.AttendanceTypeMasterClasses = new HashSet<AttendanceTypeMasterClass>();
            this.HolidayClasses = new HashSet<HolidayClass>();
            this.StudentTimeTables = new HashSet<StudentTimeTable>();
            this.TimeTableTempDetails = new HashSet<TimeTableTempDetail>();
            this.TeacherSubjectModules = new HashSet<TeacherSubjectModule>();
            this.TeacherClassAllocations = new HashSet<TeacherClassAllocation>();
        }
    
        public long RowKey { get; set; }
        public long UniversityCourseKey { get; set; }
        public Nullable<short> DivisionKey { get; set; }
        public short StudentYear { get; set; }
        public string ClassCode { get; set; }
        public Nullable<long> BuildingDetailsKey { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> LateMinutes { get; set; }
    
        public virtual BuildingDetail BuildingDetail { get; set; }
        public virtual ICollection<PromotionDetail> PromotionDetails { get; set; }
        public virtual Division Division { get; set; }
        public virtual UniversityCourse UniversityCourse { get; set; }
        public virtual ICollection<InternalExamDivision> InternalExamDivisions { get; set; }
        public virtual ICollection<InternalExamResult> InternalExamResults { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<TeacherSubjectAllocation> TeacherSubjectAllocations { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<UnitTestSchedule> UnitTestSchedules { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<StudentAbsconder> StudentAbsconders { get; set; }
        public virtual ICollection<StudentDiary> StudentDiaries { get; set; }
        public virtual ICollection<StudentDivisionAllocation> StudentDivisionAllocations { get; set; }
        public virtual ICollection<StudentEarlyDeparture> StudentEarlyDepartures { get; set; }
        public virtual ICollection<StudentLateDetail> StudentLateDetails { get; set; }
        public virtual ICollection<StudentLeaveDetail> StudentLeaveDetails { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<AttendanceTypeMasterClass> AttendanceTypeMasterClasses { get; set; }
        public virtual ICollection<HolidayClass> HolidayClasses { get; set; }
        public virtual ICollection<StudentTimeTable> StudentTimeTables { get; set; }
        public virtual ICollection<TimeTableTempDetail> TimeTableTempDetails { get; set; }
        public virtual ICollection<TeacherSubjectModule> TeacherSubjectModules { get; set; }
        public virtual ICollection<TeacherClassAllocation> TeacherClassAllocations { get; set; }
    }
}
