//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonSubjectDetail
    {
        public long RowKey { get; set; }
        public long CommonSubjectMasterKey { get; set; }
        public long CourseKey { get; set; }
        public short UniversityMasterKey { get; set; }
        public short AcademicTermKey { get; set; }
        public short CourseYear { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual CommonSubjectMaster CommonSubjectMaster { get; set; }
        public virtual Course Course { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
    }
}
