//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonSubjectMaster
    {
        public CommonSubjectMaster()
        {
            this.CommonSubjectDetails = new HashSet<CommonSubjectDetail>();
        }
    
        public long RowKey { get; set; }
        public long SubjectKey { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<CommonSubjectDetail> CommonSubjectDetails { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
