//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public short RowKey { get; set; }
        public string CompanyName { get; set; }
        public string CompanySubName { get; set; }
        public string Website { get; set; }
        public bool HasMultipleBranches { get; set; }
        public string CompanyLogo { get; set; }
        public string GSTINNumber { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
