//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactVerification
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string SMSVerificationCode { get; set; }
        public string EmailVerificationCode { get; set; }
        public Nullable<bool> IsMobileVerified { get; set; }
        public Nullable<bool> IsEmailVerfied { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
