//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Provinces = new HashSet<Province>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.EnquiryLeads1 = new HashSet<EnquiryLead>();
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee>();
            this.Enquiries = new HashSet<Enquiry>();
        }
    
        public short RowKey { get; set; }
        public string CountryName { get; set; }
        public string CountryNameLocal { get; set; }
        public string CountryShortName { get; set; }
        public string NationalityName { get; set; }
        public short LanguageKey { get; set; }
        public short CurrencyKey { get; set; }
        public string CapitalCity { get; set; }
        public string TelephoneCode { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> MinPhoneLength { get; set; }
        public Nullable<int> MaxPhoneLength { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
    }
}
