//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Books = new HashSet<Book>();
            this.CommonSubjectDetails = new HashSet<CommonSubjectDetail>();
            this.CourseSubjectMasters = new HashSet<CourseSubjectMaster>();
            this.ExamScheduleMasters = new HashSet<ExamScheduleMaster>();
            this.InternalExams = new HashSet<InternalExam>();
            this.UniversityCourses = new HashSet<UniversityCourse>();
            this.Applications = new HashSet<Application>();
            this.StudentCourseTransfers = new HashSet<StudentCourseTransfer>();
            this.StudentCourseTransfers1 = new HashSet<StudentCourseTransfer>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
            this.Enquiries = new HashSet<Enquiry>();
        }
    
        public long RowKey { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseYear { get; set; }
        public bool IsActive { get; set; }
        public short CourseTypeKey { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> DurationTypeKey { get; set; }
        public Nullable<int> DurationCount { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<CommonSubjectDetail> CommonSubjectDetails { get; set; }
        public virtual ICollection<CourseSubjectMaster> CourseSubjectMasters { get; set; }
        public virtual ICollection<ExamScheduleMaster> ExamScheduleMasters { get; set; }
        public virtual ICollection<InternalExam> InternalExams { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual ICollection<UniversityCourse> UniversityCourses { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<StudentCourseTransfer> StudentCourseTransfers { get; set; }
        public virtual ICollection<StudentCourseTransfer> StudentCourseTransfers1 { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        public virtual CourseDurationType CourseDurationType { get; set; }
    }
}
