//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSubjectDetail
    {
        public long RowKey { get; set; }
        public long CourseSubjectMasterKey { get; set; }
        public long SubjectKey { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CourseSubjectMaster CourseSubjectMaster { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
