//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.BranchDepartments = new HashSet<BranchDepartment>();
            this.DepartmentShifts = new HashSet<DepartmentShift>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.Employees = new HashSet<Employee>();
        }
    
        public short RowKey { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<BranchDepartment> BranchDepartments { get; set; }
        public virtual ICollection<DepartmentShift> DepartmentShifts { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
