//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationDetail
    {
        public long RowKey { get; set; }
        public long AssetDetailsKey { get; set; }
        public decimal Depreciation { get; set; }
        public int Period { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<long> RefKey { get; set; }
        public Nullable<decimal> ProductionUnit { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AssetPurchaseDetail AssetPurchaseDetail { get; set; }
    }
}
