//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationMethod
    {
        public DepreciationMethod()
        {
            this.AssetPurchaseDetails = new HashSet<AssetPurchaseDetail>();
            this.AssetTypes = new HashSet<AssetType>();
        }
    
        public byte RowKey { get; set; }
        public string MethodName { get; set; }
    
        public virtual ICollection<AssetPurchaseDetail> AssetPurchaseDetails { get; set; }
        public virtual ICollection<AssetType> AssetTypes { get; set; }
    }
}
