//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Branches = new HashSet<Branch>();
            this.Designation1 = new HashSet<Designation>();
            this.DesignationGrades = new HashSet<DesignationGrade>();
            this.DesignationPermissions = new HashSet<DesignationPermission>();
            this.AppUsers = new HashSet<AppUser>();
            this.Employees = new HashSet<Employee>();
        }
    
        public short RowKey { get; set; }
        public string DesignationName { get; set; }
        public Nullable<short> HigherDesignationKey { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Designation> Designation1 { get; set; }
        public virtual Designation Designation2 { get; set; }
        public virtual ICollection<DesignationGrade> DesignationGrades { get; set; }
        public virtual ICollection<DesignationPermission> DesignationPermissions { get; set; }
        public virtual ICollection<AppUser> AppUsers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
