//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Addresses = new HashSet<Address>();
            this.Branches = new HashSet<Branch>();
        }
    
        public int RowKey { get; set; }
        public string DistrictName { get; set; }
        public string DistrictNameLocal { get; set; }
        public int ProvinceKey { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual Province Province { get; set; }
    }
}
