//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTrack
    {
        public long RowKey { get; set; }
        public long AppUserKey { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> DocumentType { get; set; }
        public Nullable<long> RowDataKey { get; set; }
        public string FilePath { get; set; }
        public bool IfDownload { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
