//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationType
    {
        public EducationType()
        {
            this.EmployeeEducations = new HashSet<EmployeeEducation>();
        }
    
        public short RowKey { get; set; }
        public string EducationTypeName { get; set; }
        public string EducationTypeNameLocal { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<EmployeeEducation> EmployeeEducations { get; set; }
    }
}
