//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationQualification
    {
        public EducationQualification()
        {
            this.StudentsCertificateReturns = new HashSet<StudentsCertificateReturn>();
        }
    
        public long RowKey { get; set; }
        public string EducationQualificationCourse { get; set; }
        public string EducationQualificationUniversity { get; set; }
        public Nullable<int> EducationQualificationYear { get; set; }
        public Nullable<bool> EducationQualificationResult { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<int> EducationQualificationPercentage { get; set; }
        public string EducationQualificationCertificatePath { get; set; }
        public bool IsOriginalIssued { get; set; }
        public Nullable<System.DateTime> OriginalIssuedDate { get; set; }
        public bool IsCopyIssued { get; set; }
        public Nullable<System.DateTime> CopyIssuedDate { get; set; }
        public Nullable<bool> IsOriginalReturn { get; set; }
        public Nullable<System.DateTime> OriginalReturnDate { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public byte CertificateStatusKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> OriginalIssuedBy { get; set; }
        public Nullable<long> OriginalReturnBy { get; set; }
        public Nullable<long> VerifiedBy { get; set; }
        public string OldDocumentPath { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<StudentsCertificateReturn> StudentsCertificateReturns { get; set; }
    }
}
