//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendanceStatu
    {
        public EmployeeAttendanceStatu()
        {
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.EmployeeAttendances1 = new HashSet<EmployeeAttendance>();
            this.EmployeeAttendanceLogs = new HashSet<EmployeeAttendanceLog>();
        }
    
        public short RowKey { get; set; }
        public string AttendanceStatusCode { get; set; }
        public string AttendanceStatusName { get; set; }
        public string AttendanceStatusNameLocal { get; set; }
        public string AttendanceStatusColor { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances1 { get; set; }
        public virtual ICollection<EmployeeAttendanceLog> EmployeeAttendanceLogs { get; set; }
    }
}
