//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLanguageSkill
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public short LanguageKey { get; set; }
        public bool IsRead { get; set; }
        public bool IsWrite { get; set; }
        public bool IsSpeak { get; set; }
        public byte SkillLevelKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
