//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTask
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public string TaskTitle { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte PriorityKey { get; set; }
        public byte TaskStatusKey { get; set; }
        public short ApprovalStatusKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
