//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExperience
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhoneNumber { get; set; }
        public string JobField { get; set; }
        public string JobPostion { get; set; }
        public Nullable<System.DateTime> ExperienceStartDate { get; set; }
        public Nullable<System.DateTime> ExperianceEndDate { get; set; }
        public Nullable<decimal> StartingSalary { get; set; }
        public Nullable<decimal> EndingSalary { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNumber { get; set; }
        public string ContactPersonDesignation { get; set; }
        public string AttanchedFileName { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
