//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContact
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public long AddressKey { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
