//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEnquiryTargetDetail
    {
        public long RowKey { get; set; }
        public long EnquiryTargetKey { get; set; }
        public Nullable<int> TargetMonth { get; set; }
        public Nullable<int> TargetYear { get; set; }
        public Nullable<int> MonthlyTarget { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual EmployeeEnquiryTarget EmployeeEnquiryTarget { get; set; }
    }
}
