//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAccount
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public short BankKey { get; set; }
        public string BranchLocation { get; set; }
        public string IFSCCode { get; set; }
        public string AccountNumber { get; set; }
        public string NameInAccount { get; set; }
        public short AccountTypeKey { get; set; }
        public string MICRCode { get; set; }
        public string AdharNumber { get; set; }
        public string UANNumber { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
