//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendanceLog
    {
        public long RowKey { get; set; }
        public long AttendanceKey { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<short> AttendanceStatusKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> RefKey { get; set; }
        public Nullable<byte> AttendancePresentStatusKey { get; set; }
    
        public virtual AttendencePresentStatu AttendencePresentStatu { get; set; }
        public virtual EmployeeAttendance EmployeeAttendance { get; set; }
        public virtual EmployeeAttendanceStatu EmployeeAttendanceStatu { get; set; }
    }
}
