//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoanPayment
    {
        public long RowKey { get; set; }
        public long EmployeeLoanKey { get; set; }
        public short PaymentModeKey { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Purpose { get; set; }
        public string PaidBy { get; set; }
        public string AuthorizedBy { get; set; }
        public string ReceivedBy { get; set; }
        public string OnBehalfOf { get; set; }
        public string Remarks { get; set; }
        public string CardNumber { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public string ChequeOrDDNumber { get; set; }
        public Nullable<System.DateTime> ChequeOrDDDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual EmployeeLoan EmployeeLoan { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
