//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryAdvancePayment
    {
        public EmployeeSalaryAdvancePayment()
        {
            this.EmployeeSalaryAdvanceDetails = new HashSet<EmployeeSalaryAdvanceDetail>();
            this.EmployeeSalaryAdvanceReturnDetails = new HashSet<EmployeeSalaryAdvanceReturnDetail>();
        }
    
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public short PaymentModeKey { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Purpose { get; set; }
        public string PaidBy { get; set; }
        public string AuthorizedBy { get; set; }
        public string ReceivedBy { get; set; }
        public string OnBehalfOf { get; set; }
        public string Remarks { get; set; }
        public string CardNumber { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public string ChequeOrDDNumber { get; set; }
        public Nullable<System.DateTime> ChequeOrDDDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> ChequeStatusKey { get; set; }
        public bool IsCleared { get; set; }
        public Nullable<decimal> ClearedAmount { get; set; }
        public Nullable<long> RefKey { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<short> PaymentModeSubKey { get; set; }
        public Nullable<short> PaidBranchKey { get; set; }
        public Nullable<long> SerialNumber { get; set; }
        public string VoucherNumber { get; set; }
    
        public virtual ICollection<EmployeeSalaryAdvanceDetail> EmployeeSalaryAdvanceDetails { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual PaymentModeSub PaymentModeSub { get; set; }
        public virtual ICollection<EmployeeSalaryAdvanceReturnDetail> EmployeeSalaryAdvanceReturnDetails { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
