//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AdditionalSalaryComponents = new HashSet<AdditionalSalaryComponent>();
            this.Applications = new HashSet<Application>();
            this.Attendances = new HashSet<Attendance>();
            this.ContactVerifications = new HashSet<ContactVerification>();
            this.UnitTestSchedules = new HashSet<UnitTestSchedule>();
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.EmployeeContacts = new HashSet<EmployeeContact>();
            this.EmployeeFileHandovers = new HashSet<EmployeeFileHandover>();
            this.EmployeeFileHandovers1 = new HashSet<EmployeeFileHandover>();
            this.EmployeeIdentities = new HashSet<EmployeeIdentity>();
            this.EmployeeLanguageSkills = new HashSet<EmployeeLanguageSkill>();
            this.EmployeeLoans = new HashSet<EmployeeLoan>();
            this.EmployeeOvertimes = new HashSet<EmployeeOvertime>();
            this.EmployeeSalaryAdvancePayments = new HashSet<EmployeeSalaryAdvancePayment>();
            this.EmployeeSalaryAdvanceReturnMasters = new HashSet<EmployeeSalaryAdvanceReturnMaster>();
            this.EmployeeSalaryMasters = new HashSet<EmployeeSalaryMaster>();
            this.EmployeeShiftDetails = new HashSet<EmployeeShiftDetail>();
            this.EmployeeTasks = new HashSet<EmployeeTask>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveCarryForwards = new HashSet<LeaveCarryForward>();
            this.EmployeePFSettings = new HashSet<EmployeePFSetting>();
            this.SalaryComponents = new HashSet<SalaryComponent>();
            this.StudentTimeTables = new HashSet<StudentTimeTable>();
            this.TeacherClassAllocations = new HashSet<TeacherClassAllocation>();
            this.TeacherSubjectAllocations = new HashSet<TeacherSubjectAllocation>();
            this.TeacherSubjectModules = new HashSet<TeacherSubjectModule>();
            this.TeacherWorkScheduleDetails = new HashSet<TeacherWorkScheduleDetail>();
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.TimeTableTempMasters = new HashSet<TimeTableTempMaster>();
            this.TimeTableTempDetails = new HashSet<TimeTableTempDetail>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.DashBoardUserPermissions = new HashSet<DashBoardUserPermission>();
            this.EmployeeHierarchies = new HashSet<EmployeeHierarchy>();
            this.EmployeeHierarchies1 = new HashSet<EmployeeHierarchy>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
            this.EmployeeEnquiryTargets = new HashSet<EmployeeEnquiryTarget>();
            this.Enquiries = new HashSet<Enquiry>();
            this.EmployeeExperiences = new HashSet<EmployeeExperience>();
            this.EmployeeEducations = new HashSet<EmployeeEducation>();
            this.EmployeeAccounts = new HashSet<EmployeeAccount>();
        }
    
        public long RowKey { get; set; }
        public byte SalutationKey { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte Gender { get; set; }
        public short TelephoneCodeKey { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public bool NotificationByEmail { get; set; }
        public bool NotificationBySMS { get; set; }
        public Nullable<byte> BloodGroupKey { get; set; }
        public Nullable<short> NationalityKey { get; set; }
        public Nullable<short> ReligionKey { get; set; }
        public Nullable<short> MaritalStatusKey { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> ReleiveDate { get; set; }
        public short BranchKey { get; set; }
        public short DepartmentKey { get; set; }
        public short EmployeeCategoryKey { get; set; }
        public short DesignationKey { get; set; }
        public Nullable<int> GradeKey { get; set; }
        public short EmployeeStatusKey { get; set; }
        public string BiomatricID { get; set; }
        public string Photo { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string ContactPersonRelationship { get; set; }
        public string ContactPersonNumber { get; set; }
        public bool HasTarget { get; set; }
        public string TargetTitle { get; set; }
        public Nullable<int> TargetCount { get; set; }
        public Nullable<long> AppUserKey { get; set; }
        public Nullable<long> HigherEmployeeUserKey { get; set; }
        public string BranchAccess { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsTeacher { get; set; }
        public Nullable<byte> SalaryTypeKey { get; set; }
        public Nullable<decimal> SalaryAmount { get; set; }
        public Nullable<byte> WorkTypeKey { get; set; }
        public Nullable<short> AttendanceCategoryKey { get; set; }
        public Nullable<byte> AttendanceConfigTypeKey { get; set; }
        public Nullable<int> ShiftKey { get; set; }
        public Nullable<long> AccountHeadKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual ICollection<AdditionalSalaryComponent> AdditionalSalaryComponents { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual AttendanceCategory AttendanceCategory { get; set; }
        public virtual AttendanceConfigType AttendanceConfigType { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<ContactVerification> ContactVerifications { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual DesignationGrade DesignationGrade { get; set; }
        public virtual ICollection<UnitTestSchedule> UnitTestSchedules { get; set; }
        public virtual EmployeeCategory EmployeeCategory { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        public virtual EmployeeWorkType EmployeeWorkType { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual SalaryType SalaryType { get; set; }
        public virtual Salutation Salutation { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual EmployeeAchievement EmployeeAchievement { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<EmployeeContact> EmployeeContacts { get; set; }
        public virtual ICollection<EmployeeFileHandover> EmployeeFileHandovers { get; set; }
        public virtual ICollection<EmployeeFileHandover> EmployeeFileHandovers1 { get; set; }
        public virtual ICollection<EmployeeIdentity> EmployeeIdentities { get; set; }
        public virtual ICollection<EmployeeLanguageSkill> EmployeeLanguageSkills { get; set; }
        public virtual ICollection<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual ICollection<EmployeeOvertime> EmployeeOvertimes { get; set; }
        public virtual ICollection<EmployeeSalaryAdvancePayment> EmployeeSalaryAdvancePayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvanceReturnMaster> EmployeeSalaryAdvanceReturnMasters { get; set; }
        public virtual ICollection<EmployeeSalaryMaster> EmployeeSalaryMasters { get; set; }
        public virtual ICollection<EmployeeShiftDetail> EmployeeShiftDetails { get; set; }
        public virtual ICollection<EmployeeTask> EmployeeTasks { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        public virtual ICollection<LeaveCarryForward> LeaveCarryForwards { get; set; }
        public virtual ICollection<EmployeePFSetting> EmployeePFSettings { get; set; }
        public virtual ICollection<SalaryComponent> SalaryComponents { get; set; }
        public virtual ICollection<StudentTimeTable> StudentTimeTables { get; set; }
        public virtual ICollection<TeacherClassAllocation> TeacherClassAllocations { get; set; }
        public virtual ICollection<TeacherSubjectAllocation> TeacherSubjectAllocations { get; set; }
        public virtual ICollection<TeacherSubjectModule> TeacherSubjectModules { get; set; }
        public virtual ICollection<TeacherWorkScheduleDetail> TeacherWorkScheduleDetails { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<TimeTableTempMaster> TimeTableTempMasters { get; set; }
        public virtual ICollection<TimeTableTempDetail> TimeTableTempDetails { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<DashBoardUserPermission> DashBoardUserPermissions { get; set; }
        public virtual ICollection<EmployeeHierarchy> EmployeeHierarchies { get; set; }
        public virtual ICollection<EmployeeHierarchy> EmployeeHierarchies1 { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
        public virtual ICollection<EmployeeEnquiryTarget> EmployeeEnquiryTargets { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        public virtual ICollection<EmployeeExperience> EmployeeExperiences { get; set; }
        public virtual ICollection<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual ICollection<EmployeeAccount> EmployeeAccounts { get; set; }
    }
}
