//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOvertime
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public byte AttendanceMonth { get; set; }
        public short AttendanceYear { get; set; }
        public short TotalOvertime { get; set; }
        public Nullable<decimal> OvertimeAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
