//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public long RowKey { get; set; }
        public short EducationTypeKey { get; set; }
        public string SubjectName { get; set; }
        public string CertifiedBy { get; set; }
        public Nullable<short> CompletedYear { get; set; }
        public Nullable<short> GradigSystemKey { get; set; }
        public string Mark { get; set; }
        public string AttanchedFileName { get; set; }
        public string AttanchedFileMimeType { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public long EmployeeKey { get; set; }
    
        public virtual EducationType EducationType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
