//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryMaster
    {
        public EmployeeSalaryMaster()
        {
            this.EmployeeSalaryAdvanceDetails = new HashSet<EmployeeSalaryAdvanceDetail>();
            this.EmployeeSalaryDetails = new HashSet<EmployeeSalaryDetail>();
            this.EmployeeSalaryOtherAmounts = new HashSet<EmployeeSalaryOtherAmount>();
            this.LoanMonthlyRepayments = new HashSet<LoanMonthlyRepayment>();
            this.SalaryComponents = new HashSet<SalaryComponent>();
            this.EmployeeSalaryPayments = new HashSet<EmployeeSalaryPayment>();
        }
    
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public byte SalaryMonth { get; set; }
        public short SalaryYear { get; set; }
        public decimal MonthlySalary { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public string OtherAmountType { get; set; }
        public Nullable<decimal> PreviousBalance { get; set; }
        public decimal NoOfDaysWorked { get; set; }
        public decimal TotalSalary { get; set; }
        public short SalaryStatusKey { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string PaySlipFileName { get; set; }
        public Nullable<decimal> OverTimeAmount { get; set; }
        public Nullable<decimal> OverTimeHours { get; set; }
        public Nullable<long> RefKey { get; set; }
        public Nullable<decimal> TotalWorkingDays { get; set; }
        public Nullable<decimal> WorkingDurationHours { get; set; }
        public Nullable<byte> SalaryTypeKey { get; set; }
        public Nullable<decimal> LOP { get; set; }
        public Nullable<decimal> AdditionalDayWorked { get; set; }
        public Nullable<decimal> AdditionalDayAmount { get; set; }
        public Nullable<decimal> BaseWorkingDays { get; set; }
        public Nullable<decimal> AbsentDays { get; set; }
        public Nullable<decimal> WeekOffCount { get; set; }
        public Nullable<decimal> OffdayCount { get; set; }
        public Nullable<decimal> HolidayCount { get; set; }
        public Nullable<decimal> OverTimeTotalAmount { get; set; }
        public Nullable<decimal> OverTimeMinutes { get; set; }
        public Nullable<long> SerialNumber { get; set; }
        public string VoucherNumber { get; set; }
    
        public virtual ICollection<EmployeeSalaryAdvanceDetail> EmployeeSalaryAdvanceDetails { get; set; }
        public virtual ICollection<EmployeeSalaryDetail> EmployeeSalaryDetails { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual SalaryType SalaryType { get; set; }
        public virtual ICollection<EmployeeSalaryOtherAmount> EmployeeSalaryOtherAmounts { get; set; }
        public virtual ICollection<LoanMonthlyRepayment> LoanMonthlyRepayments { get; set; }
        public virtual ICollection<SalaryComponent> SalaryComponents { get; set; }
        public virtual ICollection<EmployeeSalaryPayment> EmployeeSalaryPayments { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
