//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public EmployeeAttendance()
        {
            this.EmployeeAttendanceLogs = new HashSet<EmployeeAttendanceLog>();
        }
    
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public short BranchKey { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> AttendanceStatusKey { get; set; }
        public Nullable<short> LeaveTypeKey { get; set; }
        public short ApprovalStatusKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> AttendanceDayStatusKey { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> TotalBreak { get; set; }
        public Nullable<int> LateComing { get; set; }
        public Nullable<int> EarlyGoing { get; set; }
        public Nullable<int> LateGoing { get; set; }
        public Nullable<int> EarlyComing { get; set; }
        public Nullable<int> ShiftKey { get; set; }
        public Nullable<int> OverTime { get; set; }
        public Nullable<int> OverTimeE { get; set; }
        public Nullable<bool> MissedInPunch { get; set; }
        public Nullable<bool> MissedOutPunch { get; set; }
        public Nullable<byte> AttendancePresentStatusKey { get; set; }
        public Nullable<byte> AttendanceConfigTypeKey { get; set; }
        public bool IsPresent { get; set; }
        public Nullable<bool> IsHalfDay { get; set; }
    
        public virtual AttendanceConfigType AttendanceConfigType { get; set; }
        public virtual AttendencePresentStatu AttendencePresentStatu { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual EmployeeAttendanceStatu EmployeeAttendanceStatu { get; set; }
        public virtual EmployeeAttendanceStatu EmployeeAttendanceStatu1 { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual ICollection<EmployeeAttendanceLog> EmployeeAttendanceLogs { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
