//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDurationConfig
    {
        public int RowKey { get; set; }
        public int MinDurationCount { get; set; }
        public Nullable<int> TotalDurationCount { get; set; }
        public string ColorCode { get; set; }
    }
}
