//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEnquiryTarget
    {
        public EmployeeEnquiryTarget()
        {
            this.EmployeeEnquiryTargetDetails = new HashSet<EmployeeEnquiryTargetDetail>();
        }
    
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public Nullable<int> CommonTarget { get; set; }
        public bool AllowMonthlyTarget { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EmployeeEnquiryTargetDetail> EmployeeEnquiryTargetDetails { get; set; }
    }
}
