//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryStatu
    {
        public EnquiryStatu()
        {
            this.EnquiryCallStatus = new HashSet<EnquiryCallStatu>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.Enquiries = new HashSet<Enquiry>();
        }
    
        public short RowKey { get; set; }
        public string EnquiryStatusCode { get; set; }
        public string EnquiryStatusDescription { get; set; }
        public string EnquiryStatusName { get; set; }
    
        public virtual ICollection<EnquiryCallStatu> EnquiryCallStatus { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
    }
}
