//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryLead
    {
        public EnquiryLead()
        {
            this.EnquiryLead1 = new HashSet<EnquiryLead>();
            this.EnquiryLeadFeedbacks = new HashSet<EnquiryLeadFeedback>();
        }
    
        public long RowKey { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Qualification { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public Nullable<short> DepartmentKey { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
        public string Feedback { get; set; }
        public string MobileNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> IsNewLead { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public string LeadFrom { get; set; }
        public Nullable<short> EnquiryLeadStatusKey { get; set; }
        public Nullable<long> EnquiryKey { get; set; }
        public string MobileNumberOptional { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> TelephoneCodeKey { get; set; }
        public Nullable<short> TelePhoneCodeOptionalkey { get; set; }
        public Nullable<long> RefLeadID { get; set; }
        public string Location { get; set; }
        public string District { get; set; }
        public Nullable<short> NatureOfEnquiryKey { get; set; }
        public Nullable<long> LeadApiKey { get; set; }
        public Nullable<long> AdsAPIKey { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual NatureOfEnquiry NatureOfEnquiry { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLead1 { get; set; }
        public virtual EnquiryLead EnquiryLead2 { get; set; }
        public virtual EnquiryStatu EnquiryStatu { get; set; }
        public virtual ICollection<EnquiryLeadFeedback> EnquiryLeadFeedbacks { get; set; }
        public virtual AdsAPI AdsAPI { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Enquiry Enquiry { get; set; }
    }
}
