//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryCallStatu
    {
        public EnquiryCallStatu()
        {
            this.EnquiryFeedbacks = new HashSet<EnquiryFeedback>();
            this.EnquiryLeadFeedbacks = new HashSet<EnquiryLeadFeedback>();
        }
    
        public int RowKey { get; set; }
        public string EnquiryCallStatusName { get; set; }
        public short EnquiryStatusKey { get; set; }
        public bool IsDuration { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string ShowInMenuKeys { get; set; }
    
        public virtual EnquiryStatu EnquiryStatu { get; set; }
        public virtual ICollection<EnquiryFeedback> EnquiryFeedbacks { get; set; }
        public virtual ICollection<EnquiryLeadFeedback> EnquiryLeadFeedbacks { get; set; }
    }
}
