//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryFeedback
    {
        public long RowKey { get; set; }
        public string EnquiryFeedbackDesc { get; set; }
        public long EnquiryKey { get; set; }
        public Nullable<System.DateTime> EnquiryFeedbackReminderDate { get; set; }
        public Nullable<bool> EnquiryFeedbackReminderStatus { get; set; }
        public Nullable<System.TimeSpan> EnquiryDuration { get; set; }
        public Nullable<byte> CallTypeKey { get; set; }
        public Nullable<int> IsCompleted { get; set; }
        public Nullable<int> EnquiryCallStatusKey { get; set; }
        public string CouncellingTime { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsLastFeedback { get; set; }
    
        public virtual CallType CallType { get; set; }
        public virtual EnquiryCallStatu EnquiryCallStatu { get; set; }
        public virtual Enquiry Enquiry { get; set; }
    }
}
