//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryLeadFeedback
    {
        public long RowKey { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.TimeSpan> CallDuration { get; set; }
        public Nullable<System.DateTime> NextCallSchedule { get; set; }
        public long EnquiryLeadKey { get; set; }
        public Nullable<byte> CallTypeKey { get; set; }
        public Nullable<int> EnquiryLeadCallStatusKey { get; set; }
        public bool EnquiryFeedbackReminderStatus { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsLastFeedback { get; set; }
    
        public virtual CallType CallType { get; set; }
        public virtual EnquiryCallStatu EnquiryCallStatu { get; set; }
        public virtual EnquiryLeadFeedback EnquiryLeadFeedback1 { get; set; }
        public virtual EnquiryLeadFeedback EnquiryLeadFeedback2 { get; set; }
        public virtual EnquiryLead EnquiryLead { get; set; }
    }
}
