//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public Enquiry()
        {
            this.Applications = new HashSet<Application>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
            this.EnquiryFeedbacks = new HashSet<EnquiryFeedback>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.Scholarships = new HashSet<Scholarship>();
        }
    
        public long RowKey { get; set; }
        public Nullable<short> AcademicTermKey { get; set; }
        public Nullable<long> CourseKey { get; set; }
        public Nullable<short> UniversityKey { get; set; }
        public string EnquiryName { get; set; }
        public string EnquiryAddress { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EnquiryEducationQualification { get; set; }
        public Nullable<short> NatureOfEnquiryKey { get; set; }
        public short BranchKey { get; set; }
        public Nullable<System.DateTime> EnquiryDateOfAdmission { get; set; }
        public string EnquiryFeedback { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<short> EnquiryStatusKey { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
        public bool IsProcessed { get; set; }
        public bool IsDeleted { get; set; }
        public string DistrictName { get; set; }
        public string LocationName { get; set; }
        public string Remarks { get; set; }
        public string MobileNumberOptional { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public short TelephoneCodeKey { get; set; }
        public Nullable<short> TelePhoneCodeOptionalkey { get; set; }
        public Nullable<short> OtherBranchKey { get; set; }
        public Nullable<short> CountryKey { get; set; }
        public Nullable<bool> IsShortlisted { get; set; }
        public string CompanyName { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EnquiryStatu EnquiryStatu { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
        public virtual NatureOfEnquiry NatureOfEnquiry { get; set; }
        public virtual ICollection<EnquiryFeedback> EnquiryFeedbacks { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<Scholarship> Scholarships { get; set; }
    }
}
