//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTest
    {
        public ExamTest()
        {
            this.ExamTestSections = new HashSet<ExamTestSection>();
        }
    
        public long RowKey { get; set; }
        public long TestPaperKey { get; set; }
        public long ApplicationKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> ExamStatusKey { get; set; }
        public string ExamKey { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual TestPaper TestPaper { get; set; }
        public virtual ICollection<ExamTestSection> ExamTestSections { get; set; }
    }
}
