//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCenter
    {
        public ExamCenter()
        {
            this.ExamSchedules = new HashSet<ExamSchedule>();
            this.ExamScheduleDetails = new HashSet<ExamScheduleDetail>();
        }
    
        public short RowKey { get; set; }
        public string ExamCentreName { get; set; }
        public string ExamCentreCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<ExamSchedule> ExamSchedules { get; set; }
        public virtual ICollection<ExamScheduleDetail> ExamScheduleDetails { get; set; }
    }
}
