//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTestAnswer
    {
        public long RowKey { get; set; }
        public int QuestionNumber { get; set; }
        public long ExamTestSectionKey { get; set; }
        public string AnswerText { get; set; }
        public bool IsCorrect { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> QuestionStatusKey { get; set; }
        public Nullable<bool> AnswerKeyStatus { get; set; }
        public Nullable<long> AnswerOptionKey { get; set; }
    
        public virtual TestQuestionOption TestQuestionOption { get; set; }
        public virtual TestQuestionOption TestQuestionOption1 { get; set; }
        public virtual TestQuestionOption TestQuestionOption2 { get; set; }
        public virtual TestQuestionOption TestQuestionOption3 { get; set; }
        public virtual TestQuestionOption TestQuestionOption4 { get; set; }
        public virtual TestQuestionOption TestQuestionOption5 { get; set; }
        public virtual TestQuestionOption TestQuestionOption6 { get; set; }
        public virtual TestQuestionOption TestQuestionOption7 { get; set; }
        public virtual TestQuestionOption TestQuestionOption8 { get; set; }
        public virtual TestQuestionOption TestQuestionOption9 { get; set; }
        public virtual QuestionStatu QuestionStatu { get; set; }
        public virtual ExamTestSection ExamTestSection { get; set; }
    }
}
