//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamScheduleMaster
    {
        public ExamScheduleMaster()
        {
            this.ExamScheduleDetails = new HashSet<ExamScheduleDetail>();
        }
    
        public long RowKey { get; set; }
        public long SubjectKey { get; set; }
        public System.DateTime ExamDate { get; set; }
        public short ExamTermKey { get; set; }
        public Nullable<decimal> MaximumMark { get; set; }
        public Nullable<decimal> MinimumMark { get; set; }
        public Nullable<System.TimeSpan> ExamStartTime { get; set; }
        public Nullable<System.TimeSpan> ExamEndTime { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> AcademicTermKey { get; set; }
        public Nullable<long> CourseKey { get; set; }
        public Nullable<short> UniversityMasterKey { get; set; }
        public Nullable<short> BatchKey { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public Nullable<short> ExamYear { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<ExamScheduleDetail> ExamScheduleDetails { get; set; }
        public virtual ExamScheduleMaster ExamScheduleMaster1 { get; set; }
        public virtual ExamScheduleMaster ExamScheduleMaster2 { get; set; }
        public virtual ExamTerm ExamTerm { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
    }
}
