//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSchedule
    {
        public ExamSchedule()
        {
            this.ExamResults = new HashSet<ExamResult>();
        }
    
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public long SubjectKey { get; set; }
        public string ExamRegisterNumber { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ExamDate { get; set; }
        public short ExamTermKey { get; set; }
        public Nullable<decimal> MaximumMark { get; set; }
        public Nullable<decimal> MinimumMark { get; set; }
        public Nullable<System.TimeSpan> ExamStartTime { get; set; }
        public Nullable<System.TimeSpan> ExamEndTime { get; set; }
        public Nullable<short> ExamCenterKey { get; set; }
        public Nullable<int> AppearenceCount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<byte> ExamStatus { get; set; }
    
        public virtual ExamCenter ExamCenter { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        public virtual ExamTerm ExamTerm { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Application Application { get; set; }
    }
}
