//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamScheduleDetail
    {
        public long RowKey { get; set; }
        public long ExamScheduleMasterKey { get; set; }
        public long ApplicationKey { get; set; }
        public string ExamRegisterNumber { get; set; }
        public Nullable<short> ExamCenterKey { get; set; }
        public Nullable<int> AppearenceCount { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ExamCenter ExamCenter { get; set; }
        public virtual ExamScheduleMaster ExamScheduleMaster { get; set; }
        public virtual Application Application { get; set; }
    }
}
