//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamType
    {
        public ExamType()
        {
            this.TestPapers = new HashSet<TestPaper>();
            this.TestPapers1 = new HashSet<TestPaper>();
            this.TestPapers2 = new HashSet<TestPaper>();
            this.TestPapers3 = new HashSet<TestPaper>();
            this.TestPapers4 = new HashSet<TestPaper>();
            this.TestPapers5 = new HashSet<TestPaper>();
            this.TestPapers6 = new HashSet<TestPaper>();
            this.TestPapers7 = new HashSet<TestPaper>();
            this.TestPapers8 = new HashSet<TestPaper>();
            this.TestPapers9 = new HashSet<TestPaper>();
        }
    
        public short RowKey { get; set; }
        public string ExamTypeName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long AddedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsShowAllQuestions { get; set; }
    
        public virtual ICollection<TestPaper> TestPapers { get; set; }
        public virtual ICollection<TestPaper> TestPapers1 { get; set; }
        public virtual ICollection<TestPaper> TestPapers2 { get; set; }
        public virtual ICollection<TestPaper> TestPapers3 { get; set; }
        public virtual ICollection<TestPaper> TestPapers4 { get; set; }
        public virtual ICollection<TestPaper> TestPapers5 { get; set; }
        public virtual ICollection<TestPaper> TestPapers6 { get; set; }
        public virtual ICollection<TestPaper> TestPapers7 { get; set; }
        public virtual ICollection<TestPaper> TestPapers8 { get; set; }
        public virtual ICollection<TestPaper> TestPapers9 { get; set; }
    }
}
