//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendFeeFollowUpDate
    {
        public long RowKey { get; set; }
        public long ApplicationFeeFollowupKey { get; set; }
        public Nullable<System.DateTime> OldFollowUpDate { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ApplicationFeeFollowup ApplicationFeeFollowup { get; set; }
    }
}
