//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee_Installment
    {
        public long InstallmentId { get; set; }
        public short BatchKey { get; set; }
        public int AcademicTermKey { get; set; }
        public short CourseTypeKey { get; set; }
        public long CourseKey { get; set; }
        public long UniversityKey { get; set; }
        public decimal FeeAmount { get; set; }
        public decimal InitialPayment { get; set; }
        public decimal BalancePayment { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
