//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCarryForwordMaster
    {
        public FeeCarryForwordMaster()
        {
            this.FeeCarryForwordDetails = new HashSet<FeeCarryForwordDetail>();
        }
    
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<decimal> CarryForwordAmount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CarryforwordDate { get; set; }
        public Nullable<long> FeePaymentMasterKey { get; set; }
    
        public virtual ICollection<FeeCarryForwordDetail> FeeCarryForwordDetails { get; set; }
        public virtual FeePaymentMaster FeePaymentMaster { get; set; }
    }
}
