//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCarryForwordDetail
    {
        public long RowKey { get; set; }
        public long FeeCarryForwordMasterKey { get; set; }
        public Nullable<long> AdmissionFeeKey { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual AdmissionFee AdmissionFee { get; set; }
        public virtual FeeCarryForwordMaster FeeCarryForwordMaster { get; set; }
    }
}
