//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeePaymentDetail
    {
        public FeePaymentDetail()
        {
            this.FeeRefundDetails = new HashSet<FeeRefundDetail>();
        }
    
        public long RowKey { get; set; }
        public short FeeTypeKey { get; set; }
        public decimal FeeAmount { get; set; }
        public Nullable<int> FeeYear { get; set; }
        public Nullable<long> FeePaymentMasterKey { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<decimal> CessAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual ICollection<FeeRefundDetail> FeeRefundDetails { get; set; }
        public virtual FeeType FeeType { get; set; }
        public virtual FeePaymentMaster FeePaymentMaster { get; set; }
    }
}
