//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeRefundDetail
    {
        public long RowKey { get; set; }
        public short FeeTypeKey { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<int> FeeYear { get; set; }
        public Nullable<long> FeeRefundMasterKey { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<long> FeePaymentDetailKey { get; set; }
    
        public virtual FeePaymentDetail FeePaymentDetail { get; set; }
        public virtual FeeRefundMaster FeeRefundMaster { get; set; }
        public virtual FeeType FeeType { get; set; }
    }
}
