//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeType
    {
        public FeeType()
        {
            this.AdmissionFees = new HashSet<AdmissionFee>();
            this.FeePaymentDetails = new HashSet<FeePaymentDetail>();
            this.FeeRefundDetails = new HashSet<FeeRefundDetail>();
            this.UniversityCourseFees = new HashSet<UniversityCourseFee>();
            this.UniversityPaymentDetails = new HashSet<UniversityPaymentDetail>();
            this.TransferAdmissionFees = new HashSet<TransferAdmissionFee>();
            this.FeeFollowUpFeeTypes = new HashSet<FeeFollowUpFeeType>();
        }
    
        public short RowKey { get; set; }
        public string FeeTypeName { get; set; }
        public byte CashFlowTypeKey { get; set; }
        public bool IsDeduct { get; set; }
        public Nullable<short> FeeTypeModeKey { get; set; }
        public bool IsTax { get; set; }
        public Nullable<short> GSTMasterkey { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsUniverisity { get; set; }
        public Nullable<long> AccountHeadKey { get; set; }
        public Nullable<short> ReceiptNumberConfigurationKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual ICollection<AdmissionFee> AdmissionFees { get; set; }
        public virtual CashFlowType CashFlowType { get; set; }
        public virtual ICollection<FeePaymentDetail> FeePaymentDetails { get; set; }
        public virtual ICollection<FeeRefundDetail> FeeRefundDetails { get; set; }
        public virtual PaymentReceiptNumberConfiguration PaymentReceiptNumberConfiguration { get; set; }
        public virtual FeeTypeMode FeeTypeMode { get; set; }
        public virtual GSTMaster GSTMaster { get; set; }
        public virtual ICollection<UniversityCourseFee> UniversityCourseFees { get; set; }
        public virtual ICollection<UniversityPaymentDetail> UniversityPaymentDetails { get; set; }
        public virtual ICollection<TransferAdmissionFee> TransferAdmissionFees { get; set; }
        public virtual ICollection<FeeFollowUpFeeType> FeeFollowUpFeeTypes { get; set; }
    }
}
