//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPassword
    {
        public long RowKey { get; set; }
        public long AppUserKey { get; set; }
        public string OTP { get; set; }
        public bool IsActive { get; set; }
        public bool IsVerified { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
