//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FutureTransactionOtherAmountType
    {
        public long RowKey { get; set; }
        public Nullable<long> FutureTransactionKey { get; set; }
        public Nullable<long> FutureTransactionPaymentKey { get; set; }
        public long AccountHeadKey { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountPer { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsAddition { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual FutureTransactionPayment FutureTransactionPayment { get; set; }
        public virtual FutureTransaction FutureTransaction { get; set; }
    }
}
