//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FutureTransaction
    {
        public FutureTransaction()
        {
            this.FutureTransactionOtherAmountTypes = new HashSet<FutureTransactionOtherAmountType>();
            this.FutureTransactionPayments = new HashSet<FutureTransactionPayment>();
        }
    
        public long RowKey { get; set; }
        public long AccountHeadKey { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public short BranchKey { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> NonTaxableAmount { get; set; }
        public Nullable<long> RefKey { get; set; }
        public Nullable<byte> OrderProcessTypeKey { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsInstallment { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public bool IsTax { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<long> HSNCodeMasterKey { get; set; }
        public Nullable<byte> InstallmentTypeKey { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public string GSTINNumber { get; set; }
        public int StateKey { get; set; }
        public byte CashFlowTypeKey { get; set; }
        public string HSNCodes { get; set; }
        public Nullable<int> InstallmentPeriod { get; set; }
        public decimal Amount { get; set; }
        public bool IsContra { get; set; }
        public Nullable<byte> InstallmentFlowKey { get; set; }
        public bool IsOpeningBalance { get; set; }
        public Nullable<decimal> OpeningReceivedAmount { get; set; }
        public Nullable<decimal> OpeningPaidAmount { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual CashFlowType CashFlowType { get; set; }
        public virtual CashFlowType CashFlowType1 { get; set; }
        public virtual ICollection<FutureTransactionOtherAmountType> FutureTransactionOtherAmountTypes { get; set; }
        public virtual ICollection<FutureTransactionPayment> FutureTransactionPayments { get; set; }
        public virtual HSNCodeMaster HSNCodeMaster { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual Province Province { get; set; }
    }
}
