//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralConfiguration
    {
        public byte RowKey { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<System.DateTime> CessFromDate { get; set; }
        public Nullable<System.DateTime> CessToDate { get; set; }
        public Nullable<bool> ShowAdminBankBalance { get; set; }
        public Nullable<bool> ShowJobTitle { get; set; }
        public Nullable<bool> NeedInclusiveGSTPrint { get; set; }
        public Nullable<byte> GenderPriority { get; set; }
        public Nullable<int> GenderPriorityCount { get; set; }
        public bool AllowAdmissionToAccoount { get; set; }
        public bool AllowSplitCostOfService { get; set; }
        public bool AllowCenterShare { get; set; }
        public bool AllowUniversityAccountHead { get; set; }
        public Nullable<byte> EducationTypeKey { get; set; }
        public Nullable<System.DateTime> FeePaymentAccountDate { get; set; }
        public Nullable<System.DateTime> UniversityPaymentAccountDate { get; set; }
        public bool AllowFeetypeOnlyIncome { get; set; }
        public bool AllowChangeAdmissionNo { get; set; }
        public bool AllowHideFeeBalance { get; set; }
        public Nullable<System.TimeSpan> ClassStartTime { get; set; }
        public Nullable<System.TimeSpan> ClassEndTime { get; set; }
        public Nullable<int> ClassLateMinutes { get; set; }
    }
}
