//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTMaster
    {
        public GSTMaster()
        {
            this.FeeTypes = new HashSet<FeeType>();
        }
    
        public short RowKey { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<FeeType> FeeTypes { get; set; }
    }
}
