//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayClass
    {
        public long RowKey { get; set; }
        public long HolidayKey { get; set; }
        public long ClassDetailsKey { get; set; }
    
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Holiday Holiday { get; set; }
    }
}
