//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public Holiday()
        {
            this.HolidayClasses = new HashSet<HolidayClass>();
        }
    
        public long RowKey { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public string HolidayTitle { get; set; }
        public string HolidayTitleLocal { get; set; }
        public Nullable<System.DateTime> HolidayFrom { get; set; }
        public Nullable<System.DateTime> HolidayTo { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public byte HolidayTypeKey { get; set; }
        public bool IsDayOff { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<HolidayClass> HolidayClasses { get; set; }
    }
}
