//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSNCodeMaster
    {
        public HSNCodeMaster()
        {
            this.FutureTransactions = new HashSet<FutureTransaction>();
            this.AssetTypes = new HashSet<AssetType>();
        }
    
        public long RowKey { get; set; }
        public string Ch { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public decimal IGST { get; set; }
        public string HSNSACCode { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual ICollection<FutureTransaction> FutureTransactions { get; set; }
        public virtual ICollection<AssetType> AssetTypes { get; set; }
    }
}
