//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalExam
    {
        public InternalExam()
        {
            this.InternalExamDetails = new HashSet<InternalExamDetail>();
            this.InternalExamDivisions = new HashSet<InternalExamDivision>();
            this.InternalExamResults = new HashSet<InternalExamResult>();
        }
    
        public long RowKey { get; set; }
        public short AcademicTermKey { get; set; }
        public long CourseKey { get; set; }
        public short UniversityMasterKey { get; set; }
        public short BatchKey { get; set; }
        public short ExamYear { get; set; }
        public short InternalExamTermKey { get; set; }
        public short BranchKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Course Course { get; set; }
        public virtual InternalExamTerm InternalExamTerm { get; set; }
        public virtual ICollection<InternalExamDetail> InternalExamDetails { get; set; }
        public virtual ICollection<InternalExamDivision> InternalExamDivisions { get; set; }
        public virtual ICollection<InternalExamResult> InternalExamResults { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
    }
}
