//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalExamDivision
    {
        public long RowKey { get; set; }
        public Nullable<long> ClassDetailsKey { get; set; }
        public Nullable<long> InternalExamKey { get; set; }
    
        public virtual InternalExam InternalExam { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
    }
}
