//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalExamResult
    {
        public long RowKey { get; set; }
        public long InternalExamKey { get; set; }
        public long ApplicationKey { get; set; }
        public long SubjectKey { get; set; }
        public string ResultStatus { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> InternalExamDetailsKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> ClassDetailsKey { get; set; }
    
        public virtual InternalExam InternalExam { get; set; }
        public virtual InternalExamDetail InternalExamDetail { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Application Application { get; set; }
    }
}
