//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalExamDetail
    {
        public InternalExamDetail()
        {
            this.InternalExamResults = new HashSet<InternalExamResult>();
        }
    
        public long RowKey { get; set; }
        public long InternalExamKey { get; set; }
        public long SubjectKey { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public bool ExamStatus { get; set; }
        public Nullable<decimal> MaximumMark { get; set; }
        public Nullable<decimal> MinimumMark { get; set; }
        public Nullable<System.TimeSpan> ExamStartTime { get; set; }
        public Nullable<System.TimeSpan> ExamEndTime { get; set; }
    
        public virtual InternalExam InternalExam { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<InternalExamResult> InternalExamResults { get; set; }
    }
}
