//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalMaster
    {
        public JournalMaster()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public long RowKey { get; set; }
        public System.DateTime JournalDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public short BranchKey { get; set; }
        public Nullable<long> RefKey { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
}
