//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public long RowKey { get; set; }
        public long MasterKey { get; set; }
        public long AccountHeadKey { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Credit { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual JournalMaster JournalMaster { get; set; }
    }
}
