//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Countries = new HashSet<Country>();
            this.EmployeeLanguageSkills = new HashSet<EmployeeLanguageSkill>();
            this.LibraryBooks = new HashSet<LibraryBook>();
            this.Provinces = new HashSet<Province>();
        }
    
        public short RowKey { get; set; }
        public string LanguageName { get; set; }
        public string LanguageNameLocal { get; set; }
        public string LanguageShortName { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<EmployeeLanguageSkill> EmployeeLanguageSkills { get; set; }
        public virtual ICollection<LibraryBook> LibraryBooks { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
    }
}
