//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.LeaveCarryForwards = new HashSet<LeaveCarryForward>();
        }
    
        public short RowKey { get; set; }
        public string LeaveTypeName { get; set; }
        public string LeaveTypeNameLocal { get; set; }
        public string LeaveTypeShortName { get; set; }
        public string LeaveTypeColor { get; set; }
        public byte LeaveCountTypeKey { get; set; }
        public int LeaveCount { get; set; }
        public bool LeaveBalanceCarryForward { get; set; }
        public bool SalaryDeductionForAdditional { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        public virtual ICollection<LeaveCarryForward> LeaveCarryForwards { get; set; }
    }
}
