//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDurationType
    {
        public LeaveDurationType()
        {
            this.LeaveApplications = new HashSet<LeaveApplication>();
        }
    
        public byte RowKey { get; set; }
        public string LeaveDurationTypeName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
    }
}
