//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public byte LeaveDurationTypeKey { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
        public short LeaveTypeKey { get; set; }
        public string LeaveReason { get; set; }
        public short LeaveStatusKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<int> LeaveUsedCount { get; set; }
    
        public virtual LeaveDurationType LeaveDurationType { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
