//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCarryForward
    {
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public Nullable<byte> MonthKey { get; set; }
        public short YearKey { get; set; }
        public short LeaveTypeKey { get; set; }
        public int LeaveBalance { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
