//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanMonthlyRepayment
    {
        public long RowKey { get; set; }
        public long SalaryMasterKey { get; set; }
        public long EmployeeLoanKey { get; set; }
        public decimal RepaymentAmount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual EmployeeLoan EmployeeLoan { get; set; }
        public virtual EmployeeSalaryMaster EmployeeSalaryMaster { get; set; }
    }
}
