//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_University
    {
        public long UniversityId { get; set; }
        public short UniversityMasterKey { get; set; }
        public Nullable<int> UniversityFeeInstalmentCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public long CourseKey { get; set; }
        public string UniversityName { get; set; }
    }
}
