//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkGroup
    {
        public MarkGroup()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
            this.TestQuestions1 = new HashSet<TestQuestion>();
            this.TestQuestions2 = new HashSet<TestQuestion>();
            this.TestQuestions3 = new HashSet<TestQuestion>();
            this.TestQuestions4 = new HashSet<TestQuestion>();
            this.TestQuestions5 = new HashSet<TestQuestion>();
            this.TestQuestions6 = new HashSet<TestQuestion>();
            this.TestQuestions7 = new HashSet<TestQuestion>();
            this.TestQuestions8 = new HashSet<TestQuestion>();
        }
    
        public int RowKey { get; set; }
        public string MarkGroupName { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<decimal> NegativeMark { get; set; }
        public long AddedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions1 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions2 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions3 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions4 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions5 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions6 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions7 { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions8 { get; set; }
    }
}
