//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRegistration
    {
        public long RowKey { get; set; }
        public short BranchKey { get; set; }
        public Nullable<int> MemberTitleKey { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public Nullable<System.DateTime> MemberDOB { get; set; }
        public string MemberPhoto { get; set; }
        public Nullable<int> IdentificationTypeKey { get; set; }
        public string IdentificationNumber { get; set; }
        public string StreetName { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateKey { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public string Gender { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string ZipCode { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual IdentificationType IdentificationType { get; set; }
        public virtual MemberTitle MemberTitle { get; set; }
        public virtual Province Province { get; set; }
    }
}
