//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuActions = new HashSet<MenuAction>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserManualMasters = new HashSet<UserManualMaster>();
        }
    
        public int RowKey { get; set; }
        public short MenuTypeKey { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public string OptionalParameter { get; set; }
        public string IconClassName { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<byte> MenuCatagoryKey { get; set; }
    
        public virtual MenuType MenuType { get; set; }
        public virtual ICollection<MenuAction> MenuActions { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual MenuCatagory MenuCatagory { get; set; }
        public virtual ICollection<UserManualMaster> UserManualMasters { get; set; }
    }
}
