//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleTopic
    {
        public ModuleTopic()
        {
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.UnitTestTopics = new HashSet<UnitTestTopic>();
        }
    
        public long RowKey { get; set; }
        public string TopicName { get; set; }
        public Nullable<long> SubjectModuleKey { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual SubjectModule SubjectModule { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<UnitTestTopic> UnitTestTopics { get; set; }
    }
}
