//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ExamTestSections = new HashSet<ExamTestSection>();
            this.TestModules = new HashSet<TestModule>();
        }
    
        public byte RowKey { get; set; }
        public string ModuleName { get; set; }
        public string SupportFileType { get; set; }
        public Nullable<decimal> MaximumBandScore { get; set; }
    
        public virtual ICollection<ExamTestSection> ExamTestSections { get; set; }
        public virtual ICollection<TestModule> TestModules { get; set; }
    }
}
