//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NatureOfEnquiry
    {
        public NatureOfEnquiry()
        {
            this.Applications = new HashSet<Application>();
            this.EnquiryLeads = new HashSet<EnquiryLead>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
            this.Enquiries = new HashSet<Enquiry>();
        }
    
        public short RowKey { get; set; }
        public string NatureOfEnquiryName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsAPI { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<EnquiryLead> EnquiryLeads { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
    }
}
