//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTemplate
    {
        public int RowKey { get; set; }
        public string NotificationTemplateName { get; set; }
        public Nullable<bool> AutoSMS { get; set; }
        public Nullable<bool> AutoEmail { get; set; }
        public string EmailTemplateFileName { get; set; }
        public string SMSTemplate { get; set; }
        public string NotificationColumnGroupKeys { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<bool> GuardianSMS { get; set; }
        public string GuardianSMSTemplate { get; set; }
        public string SMSTemplateID { get; set; }
        public string SMSTemplateName { get; set; }
        public string SMSTemplateContent { get; set; }
    }
}
