//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationColumn
    {
        public long RowKey { get; set; }
        public string NotificationColumnName { get; set; }
        public string NotificationColumnKey { get; set; }
        public int NotificationColumnGroupKey { get; set; }
        public bool IsActive { get; set; }
    
        public virtual NotificationColumnGroup NotificationColumnGroup { get; set; }
    }
}
