//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationColumnGroup
    {
        public NotificationColumnGroup()
        {
            this.NotificationColumns = new HashSet<NotificationColumn>();
        }
    
        public int RowKey { get; set; }
        public string NotificationColumnGroupName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<NotificationColumn> NotificationColumns { get; set; }
    }
}
