//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherBankTransaction
    {
        public long RowKey { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Purpose { get; set; }
        public long BankAccountKey { get; set; }
        public Nullable<short> ChequeStatusKey { get; set; }
        public string ReferenceNumber { get; set; }
        public long AccountHeadKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public long BankStatementKey { get; set; }
        public Nullable<byte> CashFlowTypeKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual BankStatementDetail BankStatementDetail { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
