//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTimeFormulaType
    {
        public OverTimeFormulaType()
        {
            this.AttendanceCategories = new HashSet<AttendanceCategory>();
        }
    
        public byte RowKey { get; set; }
        public string OTFormulaTypeName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<AttendanceCategory> AttendanceCategories { get; set; }
    }
}
