//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.AssetPurchaseMasters = new HashSet<AssetPurchaseMaster>();
        }
    
        public long RowKey { get; set; }
        public string PartyName { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string Address { get; set; }
        public byte PartyTypeKey { get; set; }
        public string Location { get; set; }
        public string EmailId { get; set; }
        public bool IsActive { get; set; }
        public int ProvinceKey { get; set; }
        public string ContactPerson { get; set; }
        public string Designation { get; set; }
        public Nullable<short> CompanyBranchKey { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
        public bool IsTax { get; set; }
        public string GSTINNumber { get; set; }
        public bool IsOpeningBalance { get; set; }
        public Nullable<byte> CashFlowTypeKey { get; set; }
        public Nullable<long> RefKey { get; set; }
        public string PartyTypes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public long AccountHeadKey { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual ICollection<AssetPurchaseMaster> AssetPurchaseMasters { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual PartyType PartyType { get; set; }
        public virtual Province Province { get; set; }
    }
}
