//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMode
    {
        public PaymentMode()
        {
            this.CashFlows = new HashSet<CashFlow>();
            this.ChequeClearances = new HashSet<ChequeClearance>();
            this.FutureTransactionPayments = new HashSet<FutureTransactionPayment>();
            this.UniversityPaymentMasters = new HashSet<UniversityPaymentMaster>();
            this.PaymentModeSubs = new HashSet<PaymentModeSub>();
            this.AssetPurchasePayments = new HashSet<AssetPurchasePayment>();
            this.EmployeeSalaryAdvancePayments = new HashSet<EmployeeSalaryAdvancePayment>();
            this.EmployeeSalaryAdvanceReturnMasters = new HashSet<EmployeeSalaryAdvanceReturnMaster>();
            this.EmployeeSalaryPayments = new HashSet<EmployeeSalaryPayment>();
            this.FeeRefundMasters = new HashSet<FeeRefundMaster>();
            this.FeePaymentMasters = new HashSet<FeePaymentMaster>();
        }
    
        public short RowKey { get; set; }
        public string PaymentModeName { get; set; }
        public string PaymentModeLocal { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<CashFlow> CashFlows { get; set; }
        public virtual ICollection<ChequeClearance> ChequeClearances { get; set; }
        public virtual ICollection<FutureTransactionPayment> FutureTransactionPayments { get; set; }
        public virtual ICollection<UniversityPaymentMaster> UniversityPaymentMasters { get; set; }
        public virtual ICollection<PaymentModeSub> PaymentModeSubs { get; set; }
        public virtual ICollection<AssetPurchasePayment> AssetPurchasePayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvancePayment> EmployeeSalaryAdvancePayments { get; set; }
        public virtual ICollection<EmployeeSalaryAdvanceReturnMaster> EmployeeSalaryAdvanceReturnMasters { get; set; }
        public virtual ICollection<EmployeeSalaryPayment> EmployeeSalaryPayments { get; set; }
        public virtual ICollection<FeeRefundMaster> FeeRefundMasters { get; set; }
        public virtual ICollection<FeePaymentMaster> FeePaymentMasters { get; set; }
    }
}
