//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptNumberConfiguration
    {
        public PaymentReceiptNumberConfiguration()
        {
            this.FeePaymentMasters = new HashSet<FeePaymentMaster>();
            this.FeeTypes = new HashSet<FeeType>();
        }
    
        public short RowKey { get; set; }
        public string ConfigName { get; set; }
        public bool IsActive { get; set; }
        public string SufixText { get; set; }
        public string PrefixText { get; set; }
        public byte LeadZeros { get; set; }
        public Nullable<long> StartValue { get; set; }
        public Nullable<long> MaxValue { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public byte Type { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<FeePaymentMaster> FeePaymentMasters { get; set; }
        public virtual ICollection<FeeType> FeeTypes { get; set; }
    }
}
