//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodType
    {
        public PeriodType()
        {
            this.FutureTransactions = new HashSet<FutureTransaction>();
            this.AssetDetails = new HashSet<AssetDetail>();
            this.AssetPurchaseDetails = new HashSet<AssetPurchaseDetail>();
        }
    
        public byte RowKey { get; set; }
        public string PeriodTypeName { get; set; }
    
        public virtual ICollection<FutureTransaction> FutureTransactions { get; set; }
        public virtual ICollection<AssetDetail> AssetDetails { get; set; }
        public virtual ICollection<AssetPurchaseDetail> AssetPurchaseDetails { get; set; }
    }
}
