//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintConfiguration
    {
        public byte RowKey { get; set; }
        public string PrintTypeName { get; set; }
        public byte PaperSizeKey { get; set; }
        public Nullable<byte> PaperOrientationKey { get; set; }
        public Nullable<byte> CopiesPerPaper { get; set; }
    
        public virtual PrintPaperSize PrintPaperSize { get; set; }
    }
}
