//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessStatu
    {
        public ProcessStatu()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.BankReconciliations = new HashSet<BankReconciliation>();
            this.EmployeeLoans = new HashSet<EmployeeLoan>();
            this.EmployeeTasks = new HashSet<EmployeeTask>();
            this.FutureTransactionPayments = new HashSet<FutureTransactionPayment>();
            this.OtherBankTransactions = new HashSet<OtherBankTransaction>();
            this.UniversityPaymentMasters = new HashSet<UniversityPaymentMaster>();
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.EmployeeSalaryMasters = new HashSet<EmployeeSalaryMaster>();
            this.LeaveApplications = new HashSet<LeaveApplication>();
            this.SalaryComponents = new HashSet<SalaryComponent>();
            this.FeeRefundMasters = new HashSet<FeeRefundMaster>();
            this.FeeRefundMasters1 = new HashSet<FeeRefundMaster>();
            this.FeePaymentMasters = new HashSet<FeePaymentMaster>();
            this.ApplicationFeeFollowups = new HashSet<ApplicationFeeFollowup>();
            this.ApplicationSchedules = new HashSet<ApplicationSchedule>();
        }
    
        public short RowKey { get; set; }
        public string ProcessStatusName { get; set; }
        public string ProcessStatusNameLocal { get; set; }
        public byte DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        public virtual ICollection<BankReconciliation> BankReconciliations { get; set; }
        public virtual ICollection<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual ICollection<EmployeeTask> EmployeeTasks { get; set; }
        public virtual ICollection<FutureTransactionPayment> FutureTransactionPayments { get; set; }
        public virtual ICollection<OtherBankTransaction> OtherBankTransactions { get; set; }
        public virtual ICollection<UniversityPaymentMaster> UniversityPaymentMasters { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<EmployeeSalaryMaster> EmployeeSalaryMasters { get; set; }
        public virtual ICollection<LeaveApplication> LeaveApplications { get; set; }
        public virtual ICollection<SalaryComponent> SalaryComponents { get; set; }
        public virtual ICollection<FeeRefundMaster> FeeRefundMasters { get; set; }
        public virtual ICollection<FeeRefundMaster> FeeRefundMasters1 { get; set; }
        public virtual ICollection<FeePaymentMaster> FeePaymentMasters { get; set; }
        public virtual ICollection<ApplicationFeeFollowup> ApplicationFeeFollowups { get; set; }
        public virtual ICollection<ApplicationSchedule> ApplicationSchedules { get; set; }
    }
}
