//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Districts = new HashSet<District>();
            this.FutureTransactions = new HashSet<FutureTransaction>();
            this.MemberRegistrations = new HashSet<MemberRegistration>();
            this.Parties = new HashSet<Party>();
        }
    
        public int RowKey { get; set; }
        public string Provincename { get; set; }
        public string ProvincenameLocal { get; set; }
        public short CountryKey { get; set; }
        public short LanguageKey { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<FutureTransaction> FutureTransactions { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<MemberRegistration> MemberRegistrations { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
    }
}
