//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationDetail
    {
        public long RowKey { get; set; }
        public long PushNotificationKey { get; set; }
        public int AppUserKey { get; set; }
        public bool IsView { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual PushNotification PushNotification { get; set; }
    }
}
