//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotification
    {
        public PushNotification()
        {
            this.PushNotificationDetails = new HashSet<PushNotificationDetail>();
        }
    
        public long RowKey { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationContent { get; set; }
        public string NotificationRedirectUrl { get; set; }
        public string NotificationClass { get; set; }
        public string NotificationIcon { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<PushNotificationDetail> PushNotificationDetails { get; set; }
    }
}
