//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationTemplate
    {
        public int RowKey { get; set; }
        public string PushNotificationName { get; set; }
        public string PushNotificationTitle { get; set; }
        public string PushNotificationContent { get; set; }
        public string PushNotificationType { get; set; }
        public bool IsActive { get; set; }
        public string PushNotificationUserKeys { get; set; }
        public string NotificationColumnKeys { get; set; }
    }
}
