//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Religion
    {
        public Religion()
        {
            this.Castes = new HashSet<Caste>();
            this.Applications = new HashSet<Application>();
            this.Employees = new HashSet<Employee>();
            this.ApplicationWebForms = new HashSet<ApplicationWebForm>();
        }
    
        public short RowKey { get; set; }
        public string ReligionName { get; set; }
        public string ReligionNameLocal { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<Caste> Castes { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<ApplicationWebForm> ApplicationWebForms { get; set; }
    }
}
