//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryType
    {
        public SalaryType()
        {
            this.EmployeeSalaryMasters = new HashSet<EmployeeSalaryMaster>();
            this.Employees = new HashSet<Employee>();
        }
    
        public byte RowKey { get; set; }
        public string SalaryTypeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<EmployeeSalaryMaster> EmployeeSalaryMasters { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
