//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryHead
    {
        public SalaryHead()
        {
            this.DesignationGradeDetails = new HashSet<DesignationGradeDetail>();
            this.EmployeeSalaryDetails = new HashSet<EmployeeSalaryDetail>();
        }
    
        public int RowKey { get; set; }
        public string SalaryHeadCode { get; set; }
        public string SalaryHeadName { get; set; }
        public string SalaryHeadNameLocal { get; set; }
        public short SalaryHeadTypeKey { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsInclude { get; set; }
        public Nullable<bool> IsFixed { get; set; }
    
        public virtual ICollection<DesignationGradeDetail> DesignationGradeDetails { get; set; }
        public virtual ICollection<EmployeeSalaryDetail> EmployeeSalaryDetails { get; set; }
        public virtual SalaryHeadType SalaryHeadType { get; set; }
    }
}
