//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        public Scholarship()
        {
            this.ScholarshipExamResults = new HashSet<ScholarshipExamResult>();
            this.ScholarshipExamSchedules = new HashSet<ScholarshipExamSchedule>();
        }
    
        public long RowKey { get; set; }
        public string ScholerShipName { get; set; }
        public string ScholerShipAddress { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string ScholerShipEducationQualification { get; set; }
        public short BranchKey { get; set; }
        public Nullable<short> ScholarshipTypeKey { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string LocationName { get; set; }
        public string Remarks { get; set; }
        public string MobileNumberOptional { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> EnquiryKey { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ScholarshipType ScholarshipType { get; set; }
        public virtual ICollection<ScholarshipExamResult> ScholarshipExamResults { get; set; }
        public virtual ICollection<ScholarshipExamSchedule> ScholarshipExamSchedules { get; set; }
        public virtual Enquiry Enquiry { get; set; }
    }
}
