//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipExamSchedule
    {
        public ScholarshipExamSchedule()
        {
            this.ScholarshipExamResults = new HashSet<ScholarshipExamResult>();
        }
    
        public long RowKey { get; set; }
        public long ScholarshipKey { get; set; }
        public Nullable<short> ScholarshipTypeKey { get; set; }
        public string ExamRegNo { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> ExamCenterKey { get; set; }
        public Nullable<System.TimeSpan> ExamStartTime { get; set; }
        public Nullable<System.TimeSpan> ExamEndTime { get; set; }
        public Nullable<long> SerialNumber { get; set; }
        public Nullable<short> ExamSubCenterKey { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Scholarship Scholarship { get; set; }
        public virtual ICollection<ScholarshipExamResult> ScholarshipExamResults { get; set; }
        public virtual ScholarshipType ScholarshipType { get; set; }
        public virtual SubBranch SubBranch { get; set; }
    }
}
