//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.DepartmentShifts = new HashSet<DepartmentShift>();
            this.EmployeeAttendances = new HashSet<EmployeeAttendance>();
            this.EmployeeShifts = new HashSet<EmployeeShift>();
            this.ShiftBreaks = new HashSet<ShiftBreak>();
            this.AttendanceConfigurations = new HashSet<AttendanceConfiguration>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int RowKey { get; set; }
        public string ShiftName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string ShiftCode { get; set; }
        public Nullable<int> PunchBeginBefore { get; set; }
        public Nullable<int> PunchEndAfter { get; set; }
        public Nullable<int> GraceTime { get; set; }
        public bool PartialDay { get; set; }
        public Nullable<byte> PartialDayKey { get; set; }
        public Nullable<System.TimeSpan> PartialDayBeginTime { get; set; }
        public Nullable<System.TimeSpan> PartialDayEndTime { get; set; }
        public System.TimeSpan BeginTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsShiftBetween { get; set; }
    
        public virtual ICollection<DepartmentShift> DepartmentShifts { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<EmployeeShift> EmployeeShifts { get; set; }
        public virtual ICollection<ShiftBreak> ShiftBreaks { get; set; }
        public virtual ICollection<AttendanceConfiguration> AttendanceConfigurations { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
