//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSetting
    {
        public int SmsId { get; set; }
        public string SmsUrl { get; set; }
        public string SmsUserName { get; set; }
        public string SmsPassword { get; set; }
        public string SmsSenderId { get; set; }
        public string SmsApiCode { get; set; }
        public string SmsRoot { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsApi { get; set; }
        public string SmsPEID { get; set; }
    }
}
