//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeInstallment
    {
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public int FeeYear { get; set; }
        public int InstallmentYear { get; set; }
        public int InstallmentMonth { get; set; }
        public int FeePaymentDay { get; set; }
        public Nullable<int> DueDuration { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> DueFineAmount { get; set; }
        public bool AutoSMS { get; set; }
        public bool AutoEmail { get; set; }
        public Nullable<int> AutoNotificationBeforeDue { get; set; }
        public Nullable<int> AutoNotificationAfterDue { get; set; }
        public Nullable<decimal> InitialPayment { get; set; }
        public Nullable<decimal> BalancePayment { get; set; }
        public Nullable<decimal> SuperFineAmount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
