//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentIDCard
    {
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public Nullable<bool> IsIssued { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<long> IssuedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
