//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTCMaster
    {
        public StudentTCMaster()
        {
            this.StudentTCDetails = new HashSet<StudentTCDetail>();
        }
    
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<System.DateTime> DateOfApplicationForTC { get; set; }
        public bool IsIssued { get; set; }
        public Nullable<long> IssuedBy { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public bool IsGenerate { get; set; }
        public Nullable<long> GeneratedBy { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> ReasonMasterKey { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<StudentTCDetail> StudentTCDetails { get; set; }
        public virtual TCReasonMaster TCReasonMaster { get; set; }
    }
}
