//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLeaveDetail
    {
        public StudentLeaveDetail()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
        }
    
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<System.DateTime> LeaveDateFrom { get; set; }
        public Nullable<System.DateTime> LeaveDateTo { get; set; }
        public string Remarks { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string ApproveRemarks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> ClassDetailsKey { get; set; }
        public Nullable<short> AttendanceTypeKey { get; set; }
        public Nullable<short> BatchKey { get; set; }
    
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Application Application { get; set; }
        public virtual Batch Batch { get; set; }
    }
}
