//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsCertificateReturn
    {
        public long RowKey { get; set; }
        public long EducationQualificationKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<long> IssuedBy { get; set; }
        public byte CertificateStatusKey { get; set; }
        public string Remaks { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsTempReturn { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual EducationQualification EducationQualification { get; set; }
    }
}
