//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTCDetail
    {
        public long RowKey { get; set; }
        public long TCMasterKey { get; set; }
        public Nullable<short> TCConfigColumnKey { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TCConfigColumn TCConfigColumn { get; set; }
        public virtual StudentTCMaster StudentTCMaster { get; set; }
    }
}
