//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseTransfer
    {
        public StudentCourseTransfer()
        {
            this.TransferAdmissionFees = new HashSet<TransferAdmissionFee>();
        }
    
        public long RowKey { get; set; }
        public Nullable<long> FromCourseKey { get; set; }
        public Nullable<short> FromUniverisityKey { get; set; }
        public Nullable<short> FromAcademicTermKey { get; set; }
        public Nullable<long> ToCourseKey { get; set; }
        public Nullable<short> ToUniverisityKey { get; set; }
        public Nullable<short> ToAcademicTermKey { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> ApplicationKey { get; set; }
        public bool IsChangeAdmissionNo { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual AcademicTerm AcademicTerm1 { get; set; }
        public virtual Application Application { get; set; }
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
        public virtual UniversityMaster UniversityMaster1 { get; set; }
        public virtual ICollection<TransferAdmissionFee> TransferAdmissionFees { get; set; }
    }
}
