//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentStudyMaterialDetail
    {
        public long RowKey { get; set; }
        public long StudentStudyMaterialKey { get; set; }
        public string StudyMaterialName { get; set; }
        public string StudyMaterialFileName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public short VisibilityTypeKey { get; set; }
        public bool AllowDownload { get; set; }
        public bool AllowPreview { get; set; }
    
        public virtual StudentStudyMaterial StudentStudyMaterial { get; set; }
        public virtual VisibilityType VisibilityType { get; set; }
    }
}
