//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubBranch
    {
        public SubBranch()
        {
            this.ScholarshipExamSchedules = new HashSet<ScholarshipExamSchedule>();
        }
    
        public short RowKey { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public string SubBranchCode { get; set; }
        public string SubBranchName { get; set; }
        public string SubBranchNameLocal { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonPhone { get; set; }
        public Nullable<short> DesignationKey { get; set; }
        public short DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<byte> TotalWorkingDays { get; set; }
        public Nullable<byte> TotalWorkingHours { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<ScholarshipExamSchedule> ScholarshipExamSchedules { get; set; }
    }
}
