//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectModule
    {
        public SubjectModule()
        {
            this.ModuleTopics = new HashSet<ModuleTopic>();
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.UnitTestSchedules = new HashSet<UnitTestSchedule>();
            this.UnitTestTopics = new HashSet<UnitTestTopic>();
            this.TeacherSubjectModules = new HashSet<TeacherSubjectModule>();
        }
    
        public long RowKey { get; set; }
        public string ModuleName { get; set; }
        public long SubjectKey { get; set; }
        public Nullable<int> Duration { get; set; }
        public bool HasTopics { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<ModuleTopic> ModuleTopics { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<UnitTestSchedule> UnitTestSchedules { get; set; }
        public virtual ICollection<UnitTestTopic> UnitTestTopics { get; set; }
        public virtual ICollection<TeacherSubjectModule> TeacherSubjectModules { get; set; }
    }
}
