//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.CommonSubjectMasters = new HashSet<CommonSubjectMaster>();
            this.CourseSubjectDetails = new HashSet<CourseSubjectDetail>();
            this.ElectivePapers = new HashSet<ElectivePaper>();
            this.ExamResults = new HashSet<ExamResult>();
            this.ExamSchedules = new HashSet<ExamSchedule>();
            this.ExamScheduleMasters = new HashSet<ExamScheduleMaster>();
            this.InternalExamDetails = new HashSet<InternalExamDetail>();
            this.InternalExamResults = new HashSet<InternalExamResult>();
            this.StudyMaterials = new HashSet<StudyMaterial>();
            this.SubjectModules = new HashSet<SubjectModule>();
            this.TeacherSubjectAllocations = new HashSet<TeacherSubjectAllocation>();
            this.TeacherWorkScheduleMasters = new HashSet<TeacherWorkScheduleMaster>();
            this.UnitTestSchedules = new HashSet<UnitTestSchedule>();
            this.UnitTestTopics = new HashSet<UnitTestTopic>();
            this.StudentTimeTables = new HashSet<StudentTimeTable>();
            this.TimeTableTempDetails = new HashSet<TimeTableTempDetail>();
            this.TeacherSubjectModules = new HashSet<TeacherSubjectModule>();
            this.TestPapers = new HashSet<TestPaper>();
            this.Videos = new HashSet<Video>();
            this.StudentStudyMaterials = new HashSet<StudentStudyMaterial>();
        }
    
        public long RowKey { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public bool IsElective { get; set; }
        public Nullable<short> StudyMaterialCount { get; set; }
        public bool HasStudyMaterial { get; set; }
        public bool IsCommonSubject { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<CommonSubjectMaster> CommonSubjectMasters { get; set; }
        public virtual ICollection<CourseSubjectDetail> CourseSubjectDetails { get; set; }
        public virtual ICollection<ElectivePaper> ElectivePapers { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        public virtual ICollection<ExamSchedule> ExamSchedules { get; set; }
        public virtual ICollection<ExamScheduleMaster> ExamScheduleMasters { get; set; }
        public virtual ICollection<InternalExamDetail> InternalExamDetails { get; set; }
        public virtual ICollection<InternalExamResult> InternalExamResults { get; set; }
        public virtual ICollection<StudyMaterial> StudyMaterials { get; set; }
        public virtual ICollection<SubjectModule> SubjectModules { get; set; }
        public virtual ICollection<TeacherSubjectAllocation> TeacherSubjectAllocations { get; set; }
        public virtual ICollection<TeacherWorkScheduleMaster> TeacherWorkScheduleMasters { get; set; }
        public virtual ICollection<UnitTestSchedule> UnitTestSchedules { get; set; }
        public virtual ICollection<UnitTestTopic> UnitTestTopics { get; set; }
        public virtual ICollection<StudentTimeTable> StudentTimeTables { get; set; }
        public virtual ICollection<TimeTableTempDetail> TimeTableTempDetails { get; set; }
        public virtual ICollection<TeacherSubjectModule> TeacherSubjectModules { get; set; }
        public virtual ICollection<TestPaper> TestPapers { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<StudentStudyMaterial> StudentStudyMaterials { get; set; }
    }
}
