//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRack
    {
        public SubRack()
        {
            this.LibraryBooks = new HashSet<LibraryBook>();
        }
    
        public long RowKey { get; set; }
        public int RackKey { get; set; }
        public string SubRackName { get; set; }
        public string SubRackCode { get; set; }
    
        public virtual ICollection<LibraryBook> LibraryBooks { get; set; }
        public virtual Rack Rack { get; set; }
    }
}
