//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCConfigColumn
    {
        public TCConfigColumn()
        {
            this.StudentTCDetails = new HashSet<StudentTCDetail>();
        }
    
        public short RowKey { get; set; }
        public string ColumnName { get; set; }
        public Nullable<short> CondentTypeKey { get; set; }
        public string ColumnValue { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Descreption { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public bool IsDeletable { get; set; }
    
        public virtual CondentType CondentType { get; set; }
        public virtual ICollection<StudentTCDetail> StudentTCDetails { get; set; }
    }
}
