//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherWorkScheduleMaster
    {
        public TeacherWorkScheduleMaster()
        {
            this.TeacherWorkScheduleDetails = new HashSet<TeacherWorkScheduleDetail>();
        }
    
        public long RowKey { get; set; }
        public long ClassDetailsKey { get; set; }
        public long SubjectKey { get; set; }
        public Nullable<long> SubjectModuleKey { get; set; }
        public short BranchKey { get; set; }
        public short BatchKey { get; set; }
        public Nullable<long> TopicKey { get; set; }
        public Nullable<int> ProgressStatus { get; set; }
        public Nullable<long> ScheduledEmployeeKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ModuleTopic ModuleTopic { get; set; }
        public virtual SubjectModule SubjectModule { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<TeacherWorkScheduleDetail> TeacherWorkScheduleDetails { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
