//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherClassAllocation
    {
        public TeacherClassAllocation()
        {
            this.TeacherSubjectAllocations = new HashSet<TeacherSubjectAllocation>();
            this.TeacherSubjectModules = new HashSet<TeacherSubjectModule>();
        }
    
        public long RowKey { get; set; }
        public long EmployeeKey { get; set; }
        public Nullable<long> ClassDetailsKey { get; set; }
        public bool InCharge { get; set; }
        public bool IsActive { get; set; }
        public bool IsAttendance { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<short> BatchKey { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual ICollection<TeacherSubjectAllocation> TeacherSubjectAllocations { get; set; }
        public virtual ICollection<TeacherSubjectModule> TeacherSubjectModules { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
