//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherWorkScheduleDetail
    {
        public long RowKey { get; set; }
        public long TecherScheduleMasterKey { get; set; }
        public System.DateTime WorkScheduleDate { get; set; }
        public int Duration { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<int> CurrentProgressStatus { get; set; }
        public long EmployeeKey { get; set; }
    
        public virtual TeacherWorkScheduleMaster TeacherWorkScheduleMaster { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
