//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        public long RowKey { get; set; }
        public long TestSectionKey { get; set; }
        public byte QuestionTypeKey { get; set; }
        public int QuestionNumber { get; set; }
        public string AnswerKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<decimal> NegativeMark { get; set; }
        public Nullable<int> MarkGroupKey { get; set; }
        public Nullable<int> QuestionDuration { get; set; }
    
        public virtual MarkGroup MarkGroup { get; set; }
        public virtual MarkGroup MarkGroup1 { get; set; }
        public virtual MarkGroup MarkGroup2 { get; set; }
        public virtual MarkGroup MarkGroup3 { get; set; }
        public virtual MarkGroup MarkGroup4 { get; set; }
        public virtual MarkGroup MarkGroup5 { get; set; }
        public virtual MarkGroup MarkGroup6 { get; set; }
        public virtual MarkGroup MarkGroup7 { get; set; }
        public virtual MarkGroup MarkGroup8 { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual TestSection TestSection { get; set; }
    }
}
