//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestModule
    {
        public TestModule()
        {
            this.TestSections = new HashSet<TestSection>();
        }
    
        public long RowKey { get; set; }
        public long TestPaperKey { get; set; }
        public Nullable<int> TestDuration { get; set; }
        public byte ModuleKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual TestPaper TestPaper { get; set; }
        public virtual ICollection<TestSection> TestSections { get; set; }
    }
}
