//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        public TestPaper()
        {
            this.ExamTests = new HashSet<ExamTest>();
            this.TestModules = new HashSet<TestModule>();
        }
    
        public long RowKey { get; set; }
        public string TestPaperName { get; set; }
        public string InstructionFile { get; set; }
        public string PlanKeys { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<long> SubjectKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AcademicTermKeys { get; set; }
        public string CourseTypeKeys { get; set; }
        public string CourseKeys { get; set; }
        public string UniversityKeys { get; set; }
        public string MeadiumKeys { get; set; }
        public string SecondLanguageKeys { get; set; }
        public string BatchKeys { get; set; }
        public string ModeKeys { get; set; }
        public string StartYearKeys { get; set; }
        public string ClassModeKeys { get; set; }
        public string ClassCodeKeys { get; set; }
        public string BranchKeys { get; set; }
        public string SubjectKeys { get; set; }
        public Nullable<short> ExamTypeKey { get; set; }
    
        public virtual ICollection<ExamTest> ExamTests { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual ExamType ExamType1 { get; set; }
        public virtual ExamType ExamType2 { get; set; }
        public virtual ExamType ExamType3 { get; set; }
        public virtual ExamType ExamType4 { get; set; }
        public virtual ExamType ExamType5 { get; set; }
        public virtual ExamType ExamType6 { get; set; }
        public virtual ExamType ExamType7 { get; set; }
        public virtual ExamType ExamType8 { get; set; }
        public virtual ExamType ExamType9 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<TestModule> TestModules { get; set; }
    }
}
