//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSection
    {
        public TestSection()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
            this.TestQuestionOptions = new HashSet<TestQuestionOption>();
        }
    
        public long RowKey { get; set; }
        public long TestModuleKey { get; set; }
        public string SectionName { get; set; }
        public string SupportFile { get; set; }
        public string QuestionPaperFile { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string QuestionContent { get; set; }
    
        public virtual TestModule TestModule { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        public virtual ICollection<TestQuestionOption> TestQuestionOptions { get; set; }
    }
}
