//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestionOption
    {
        public TestQuestionOption()
        {
            this.ExamTestAnswers = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers1 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers2 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers3 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers4 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers5 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers6 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers7 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers8 = new HashSet<ExamTestAnswer>();
            this.ExamTestAnswers9 = new HashSet<ExamTestAnswer>();
        }
    
        public long RowKey { get; set; }
        public long TestSectionKey { get; set; }
        public string OptionText { get; set; }
        public string OptionValue { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers1 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers2 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers3 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers4 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers5 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers6 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers7 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers8 { get; set; }
        public virtual ICollection<ExamTestAnswer> ExamTestAnswers9 { get; set; }
        public virtual TestSection TestSection { get; set; }
    }
}
