//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.AccountFlows = new HashSet<AccountFlow>();
        }
    
        public byte RowKey { get; set; }
        public string TransactionTypeName { get; set; }
        public string TransactionTypeNameLocal { get; set; }
        public short StatusKey { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<AccountFlow> AccountFlows { get; set; }
    }
}
