//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTestSchedule
    {
        public UnitTestSchedule()
        {
            this.UnitTestResults = new HashSet<UnitTestResult>();
            this.UnitTestTopics = new HashSet<UnitTestTopic>();
        }
    
        public long RowKey { get; set; }
        public short BatchKey { get; set; }
        public long ClassDetailsKey { get; set; }
        public System.DateTime ExamDate { get; set; }
        public short BranchKey { get; set; }
        public Nullable<long> SubjectKey { get; set; }
        public Nullable<long> SubjectModuleKey { get; set; }
        public Nullable<decimal> MaximumMark { get; set; }
        public Nullable<decimal> MinimumMark { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual SubjectModule SubjectModule { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<UnitTestResult> UnitTestResults { get; set; }
        public virtual ICollection<UnitTestTopic> UnitTestTopics { get; set; }
        public virtual ClassDetail ClassDetail { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
