//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityPaymentMaster
    {
        public UniversityPaymentMaster()
        {
            this.UniversityPaymentDetails = new HashSet<UniversityPaymentDetail>();
        }
    
        public long RowKey { get; set; }
        public string UniversityPaymentChalanDDNumber { get; set; }
        public short PaymentModeKey { get; set; }
        public System.DateTime UniversityPaymentDate { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public string UniversityPaymentNote { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<decimal> CenterShareAmount { get; set; }
        public long SerialNumber { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> ChequeClearanceDate { get; set; }
        public Nullable<System.DateTime> ChequeApprovedRejectedDate { get; set; }
        public Nullable<short> ChequeStatusKey { get; set; }
        public Nullable<bool> IsChequeProcessCompleted { get; set; }
        public string ChequeRejectedRemarks { get; set; }
        public string ChequeOrDDNumber { get; set; }
        public Nullable<short> PaymentModeSubKey { get; set; }
        public string CardNumber { get; set; }
        public Nullable<short> PaidBranchKey { get; set; }
    
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual ICollection<UniversityPaymentDetail> UniversityPaymentDetails { get; set; }
        public virtual Application Application { get; set; }
        public virtual PaymentModeSub PaymentModeSub { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
