//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityPaymentCancelation
    {
        public long RowKey { get; set; }
        public long ApplicationKey { get; set; }
        public Nullable<long> UniversityPaymentDetailsKey { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool IfServiceCharge { get; set; }
        public Nullable<long> AccountHeadKey { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public Nullable<decimal> TotalDeductionFee { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
        public virtual UniversityPaymentDetail UniversityPaymentDetail { get; set; }
    }
}
