//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityCourse
    {
        public UniversityCourse()
        {
            this.UniversityCourseFees = new HashSet<UniversityCourseFee>();
            this.UniversityCourseFeeInstallments = new HashSet<UniversityCourseFeeInstallment>();
            this.ClassDetails = new HashSet<ClassDetail>();
        }
    
        public long RowKey { get; set; }
        public short UniversityMasterKey { get; set; }
        public long CourseKey { get; set; }
        public short AcademicTermKey { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<UniversityCourseFee> UniversityCourseFees { get; set; }
        public virtual ICollection<UniversityCourseFeeInstallment> UniversityCourseFeeInstallments { get; set; }
        public virtual ICollection<ClassDetail> ClassDetails { get; set; }
        public virtual UniversityMaster UniversityMaster { get; set; }
    }
}
