//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityCourseFee
    {
        public long RowKey { get; set; }
        public long UniversityCourseKey { get; set; }
        public Nullable<short> FeeTypeKey { get; set; }
        public Nullable<short> FeeYear { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<decimal> CenterShareAmountPer { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual UniversityCourse UniversityCourse { get; set; }
        public virtual FeeType FeeType { get; set; }
    }
}
