//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManualMaster
    {
        public UserManualMaster()
        {
            this.UserManualDetails = new HashSet<UserManualDetail>();
        }
    
        public long RowKey { get; set; }
        public short UserManualTypeKey { get; set; }
        public Nullable<short> DashBoardTypeKey { get; set; }
        public Nullable<short> MenuTypeKey { get; set; }
        public Nullable<int> MenuKey { get; set; }
        public string Descreption { get; set; }
        public string DocumentPath { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual DashBoardType DashBoardType { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual MenuType MenuType { get; set; }
        public virtual ICollection<UserManualDetail> UserManualDetails { get; set; }
        public virtual UserManualType UserManualType { get; set; }
    }
}
