//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoDetail
    {
        public long RowKey { get; set; }
        public string VideoFileName { get; set; }
        public string VideoDescription { get; set; }
        public long VideoKey { get; set; }
        public short VisibilityTypeKey { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool AllowDownload { get; set; }
        public Nullable<byte> VideoTypeKey { get; set; }
        public string YoutubeLink { get; set; }
    
        public virtual Video Video { get; set; }
        public virtual VisibilityType VisibilityType { get; set; }
    }
}
