//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LibraryBookCopy
    {
        public long BookCopyKey { get; set; }
        public long BookKey { get; set; }
        public string BookCopySlNo { get; set; }
        public long SerialNo { get; set; }
        public string ISBN { get; set; }
        public string BookBarCode { get; set; }
        public string BookEdition { get; set; }
        public Nullable<short> BookPrintYear { get; set; }
        public Nullable<short> NoOfPages { get; set; }
        public decimal BookPrice { get; set; }
        public decimal FineAmount { get; set; }
        public System.DateTime BookCopyCreatedDate { get; set; }
        public long BookCopyAddedBy { get; set; }
        public Nullable<bool> BookCopyActive { get; set; }
        public string BookName { get; set; }
        public string BookName_Optional { get; set; }
        public string BookCode { get; set; }
        public string CoverPhoto { get; set; }
        public int AuthorKey { get; set; }
        public string AuthorName { get; set; }
        public string BookCategoryName { get; set; }
        public short BookCategoryKey { get; set; }
        public byte BookIssueTypeKey { get; set; }
        public string BookIssueTypeName { get; set; }
        public short LanguageKey { get; set; }
        public string LanguageName { get; set; }
        public short BranchKey { get; set; }
        public string BranchName { get; set; }
        public int PublisherKey { get; set; }
        public string PublisherName { get; set; }
        public Nullable<long> SubRackKey { get; set; }
        public string SubRackName { get; set; }
        public int RackKey { get; set; }
        public string RackName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long AddedBy { get; set; }
        public string AppUserName { get; set; }
        public bool IsActive { get; set; }
    }
}
