//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAccountHeadSelectActiveOnly
    {
        public string AccountHeadCode { get; set; }
        public long RowKey { get; set; }
        public string AccountHeadName { get; set; }
        public short AccountHeadTypeKey { get; set; }
        public long DisplayOrder { get; set; }
    }
}
