//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwBankPaymentSelect
    {
        public Nullable<short> BranchKey { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string StudentName { get; set; }
        public Nullable<long> AccountHeadKey { get; set; }
        public Nullable<byte> TransactionTypeKey { get; set; }
        public long TransactionKey { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsAdvance { get; set; }
        public Nullable<byte> CashFlowTypeKey { get; set; }
        public Nullable<long> BankAccountKey { get; set; }
        public string Purpose { get; set; }
        public string TransactionTypeName { get; set; }
        public Nullable<short> PaymentModeKey { get; set; }
    }
}
