//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwBookSelectActiveOnly
    {
        public long RowKey { get; set; }
        public string SubjectName { get; set; }
        public string SubjectCode { get; set; }
        public bool IsElective { get; set; }
        public Nullable<short> StudyMaterialCount { get; set; }
        public bool HasStudyMaterial { get; set; }
        public bool IsCommonSubject { get; set; }
        public bool IsActive { get; set; }
        public long CourseKey { get; set; }
        public short UniversityMasterKey { get; set; }
        public short AcademicTermKey { get; set; }
        public short CourseYear { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
