//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCountrySelectAll
    {
        public short RowKey { get; set; }
        public string CountryName { get; set; }
        public string CountryNameLocal { get; set; }
        public string CountryShortName { get; set; }
        public string NationalityName { get; set; }
        public short LanguageKey { get; set; }
        public string CapitalCity { get; set; }
        public string TelephoneCode { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
