//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCourseSelectActiveOnly
    {
        public long RowKey { get; set; }
        public string CourseName { get; set; }
        public short CourseTypeKey { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
