//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwEnquiryFeedbackReportSelectAll
    {
        public long RowKey { get; set; }
        public long FeedbackKey { get; set; }
        public string ServiceType { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string EmployeeName { get; set; }
        public string CreatedBy { get; set; }
        public string ScheduledEmployeeName { get; set; }
        public string Branch { get; set; }
        public string Program { get; set; }
        public string Country { get; set; }
        public string Qualification { get; set; }
        public string Location { get; set; }
        public string District { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<short> EnquiryStatusKey { get; set; }
        public Nullable<long> EmployeeKey { get; set; }
        public int ScheduledEmployeeKey { get; set; }
        public int CountryKey { get; set; }
        public Nullable<int> ApplicationStatusKey { get; set; }
        public int ScheduleType { get; set; }
        public Nullable<System.TimeSpan> CallDuration { get; set; }
        public Nullable<int> CallStatusKey { get; set; }
        public System.DateTime CalledDate { get; set; }
        public Nullable<System.DateTime> NextScheduleDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ReminderStatusKey { get; set; }
        public long ScheduleKey { get; set; }
        public string EnquiryCallStatusName { get; set; }
        public string Feedback { get; set; }
        public long LeadEnquiryKey { get; set; }
        public string CallTypeName { get; set; }
        public int IsClose { get; set; }
        public int DocumentRowKey { get; set; }
        public int RefundKey { get; set; }
        public string ApplicationStatusName { get; set; }
        public string StatusName { get; set; }
        public Nullable<byte> CallTypeKey { get; set; }
        public Nullable<int> OtherBranchKey { get; set; }
        public string CounsellingBranchName { get; set; }
        public Nullable<short> BranchKey { get; set; }
        public int FeedbackAddedBy { get; set; }
        public int AppUserKey { get; set; }
        public Nullable<int> CounsellingBranchKey { get; set; }
        public string EnquiryStatusNameOnCall { get; set; }
        public Nullable<int> EnquiryStatusKeyOnCall { get; set; }
        public string ScheduleTypeName { get; set; }
        public Nullable<int> EmployeeAppUserKey { get; set; }
        public Nullable<System.DateTime> LeadAddedEnquiryDate { get; set; }
        public Nullable<int> ApplicationEnquiryKey { get; set; }
        public string CounsellingTime { get; set; }
        public Nullable<int> ApplicationFeeRefundAddedDate { get; set; }
        public Nullable<short> AcademicTermKey { get; set; }
        public int ScheduledEmployeeAppUserKey { get; set; }
        public Nullable<short> TelephoneCodeKey { get; set; }
        public Nullable<short> EmployeeBranchKey { get; set; }
        public int ScheduledBranchKey { get; set; }
        public Nullable<long> LastScheduleKey { get; set; }
    }
}
