//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSelectBulkEmailSm
    {
        public long RowKey { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<short> RoleKey { get; set; }
        public short BranchKey { get; set; }
        public Nullable<short> StudentStatusKey { get; set; }
        public long EmployeeKey { get; set; }
        public Nullable<long> CourseKey { get; set; }
        public Nullable<short> CourseTypeKey { get; set; }
        public Nullable<short> UniversityMasterKey { get; set; }
        public Nullable<short> BatchKey { get; set; }
        public Nullable<short> AcademicTermKey { get; set; }
        public Nullable<short> CurrentYear { get; set; }
        public string CourseName { get; set; }
        public string UniversityMasterName { get; set; }
        public string AcademicTermName { get; set; }
        public string BatchName { get; set; }
        public string CourseTypeName { get; set; }
        public string DesignationName { get; set; }
    }
}
