//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSelectMarkGroup
    {
        public int RowKey { get; set; }
        public string MarkGroupName { get; set; }
        public string MarkGroupName2 { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<decimal> NegativeMark { get; set; }
    }
}
