//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITS.EduSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwTeacherSelectActiveOnly
    {
        public long RowKey { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsTeacher { get; set; }
        public Nullable<long> ClassDetailsKey { get; set; }
        public Nullable<short> BatchKey { get; set; }
        public short BranchKey { get; set; }
    }
}
